const CHARACTERS = [
  {id:"baiqi",name:"白起",country:"秦",born:-332,died:-257,type:"武将",military:98,governance:30,diplomacy:20,strategy:85,loyalty:70,desc:"战国四大名将之首，杀神。伊阙之战斩首二十四万，长平之战坑杀赵卒四十万。"},
  {id:"wangjian",name:"王翦",country:"秦",born:-290,died:-220,type:"武将",military:95,governance:50,diplomacy:40,strategy:90,loyalty:85,desc:"战国四大名将之一，灭赵灭燕灭楚，与子王贲为秦统一最大功臣。"},
  {id:"shangyang",name:"商鞅",country:"秦",born:-395,died:-338,type:"谋士",military:40,governance:98,diplomacy:50,strategy:95,loyalty:80,desc:"法家代表，入秦行变法，使秦由弱转强。然秦孝公死后被车裂。"},
  {id:"zhangyi",name:"张仪",country:"秦",born:-378,died:-309,type:"谋士",military:20,governance:60,diplomacy:98,strategy:90,loyalty:75,desc:"纵横家，连横之策破合纵，以三寸之舌强于百万之师。"},
  {id:"fanju",name:"范雎",country:"秦",born:-310,died:-255,type:"文官",military:30,governance:85,diplomacy:80,strategy:85,loyalty:70,desc:"远交近攻之策的提出者，助秦昭襄王巩固王权。"},
  {id:"lvbuwei",name:"吕不韦",country:"秦",born:-292,died:-235,type:"文官",military:25,governance:80,diplomacy:85,strategy:75,loyalty:60,desc:"奇货可居，以商人之身助嬴异人即位，官至秦相。"},
  {id:"lisi",name:"李斯",country:"秦",born:-280,died:-208,type:"文官",military:15,governance:90,diplomacy:70,strategy:80,loyalty:65,desc:"荀子门生，法家集大成者，助秦始皇统一文字度量。"},
  {id:"mengao",name:"蒙骜",country:"秦",born:-320,died:-240,type:"武将",military:82,governance:35,diplomacy:25,strategy:70,loyalty:85,desc:"秦国名将，历仕四朝，攻城略地无数。"},
  {id:"simacuo",name:"司马错",country:"秦",born:-350,died:-280,type:"武将",military:80,governance:45,diplomacy:35,strategy:78,loyalty:80,desc:"灭蜀之将，为秦夺取巴蜀粮仓。"},
  {id:"lianpo",name:"廉颇",country:"赵",born:-327,died:-243,type:"武将",military:92,governance:40,diplomacy:30,strategy:80,loyalty:85,desc:"战国四大名将之一，长平之战前坚守不出，老成持重。"},
  {id:"limu",name:"李牧",country:"赵",born:-290,died:-229,type:"武将",military:95,governance:50,diplomacy:30,strategy:92,loyalty:90,desc:"战国四大名将之一，北抗匈奴，西拒强秦，赵国最后的柱石。"},
  {id:"zhaoshe",name:"赵奢",country:"赵",born:-320,died:-270,type:"武将",military:82,governance:55,diplomacy:30,strategy:75,loyalty:85,desc:"阏与之战大败秦军，赐号马服君。"},
  {id:"linxiangru",name:"蔺相如",country:"赵",born:-320,died:-260,type:"文官",military:20,governance:80,diplomacy:95,strategy:75,loyalty:95,desc:"完璧归赵、渑池之会，以智勇保全赵国尊严。"},
  {id:"feiyi",name:"肥义",country:"赵",born:-350,died:-295,type:"文官",military:40,governance:75,diplomacy:50,strategy:70,loyalty:95,desc:"赵武灵王托孤重臣，忠心不二，死于沙丘之乱。"},
  {id:"pingyuan",name:"平原君",country:"赵",born:-308,died:-251,type:"文官",military:35,governance:70,diplomacy:80,strategy:65,loyalty:85,desc:"赵胜，战国四公子之一，门客三千。"},
  {id:"sunbin",name:"孙膑",country:"齐",born:-382,died:-316,type:"谋士",military:70,governance:40,diplomacy:45,strategy:98,loyalty:80,desc:"兵家圣手，桂陵之战围魏救赵，马陵之战减灶诱敌。"},
  {id:"tianji",name:"田忌",country:"齐",born:-370,died:-310,type:"武将",military:78,governance:40,diplomacy:35,strategy:70,loyalty:75,desc:"齐国名将，桂陵、马陵之战主将。"},
  {id:"tianjin",name:"田单",country:"齐",born:-310,died:-260,type:"武将",military:88,governance:55,diplomacy:40,strategy:85,loyalty:85,desc:"火牛阵复齐，以即墨一城反攻，收复七十余城。"},
  {id:"zouji",name:"邹忌",country:"齐",born:-385,died:-320,type:"文官",military:15,governance:85,diplomacy:70,strategy:65,loyalty:80,desc:"齐相，以鼓琴谏齐威王，邹忌讽齐王纳谏。"},
  {id:"mengchang",name:"孟尝君",country:"齐",born:-320,died:-279,type:"文官",military:30,governance:65,diplomacy:85,strategy:60,loyalty:70,desc:"田文，战国四公子之一，鸡鸣狗盗，门客三千。"},
  {id:"leiyi",name:"乐毅",country:"燕",born:-310,died:-260,type:"武将",military:92,governance:60,diplomacy:50,strategy:90,loyalty:80,desc:"率五国联军伐齐，下七十余城，封昌国君。"},
  {id:"jike",name:"骑劫",country:"燕",born:-300,died:-279,type:"武将",military:45,governance:25,diplomacy:20,strategy:30,loyalty:70,desc:"燕将，代乐毅为将，为田单火牛阵所败。"},
  {id:"suqin",name:"苏秦",country:"燕",born:-337,died:-284,type:"谋士",military:15,governance:50,diplomacy:98,strategy:88,loyalty:75,desc:"合纵之策的倡导者，佩六国相印。实为燕国间谍。"},
  {id:"wuqi",name:"吴起",country:"魏",born:-440,died:-381,type:"谋士",military:90,governance:92,diplomacy:40,strategy:90,loyalty:65,desc:"兵家亚圣，在魏创武卒，在楚行变法，终为贵族所杀。"},
  {id:"ximenbao",name:"西门豹",country:"魏",born:-430,died:-370,type:"文官",military:25,governance:90,diplomacy:40,strategy:60,loyalty:85,desc:"治邺名臣，破除河伯娶妇迷信，兴修水利。"},
  {id:"xinling",name:"信陵君",country:"魏",born:-298,died:-243,type:"文官",military:60,governance:65,diplomacy:85,strategy:80,loyalty:90,desc:"魏无忌，战国四公子之首，窃符救赵，率五国败秦。"},
  {id:"pangjuan",name:"庞涓",country:"魏",born:-375,died:-341,type:"武将",military:78,governance:30,diplomacy:25,strategy:65,loyalty:80,desc:"魏将，与孙膑同师鬼谷，马陵之战兵败自刎。"},
  {id:"shenbuhai",name:"申不害",country:"韩",born:-400,died:-337,type:"谋士",military:25,governance:88,diplomacy:50,strategy:78,loyalty:80,desc:"法家术派代表，相韩十五年，内修政教，外应诸侯。"},
  {id:"hanfei",name:"韩非",country:"韩",born:-280,died:-233,type:"谋士",military:10,governance:95,diplomacy:40,strategy:88,loyalty:85,desc:"法家集大成者，著《韩非子》，口吃不善言而善著书。"},
  {id:"zhangliang",name:"张良",country:"韩",born:-250,died:-186,type:"谋士",military:30,governance:60,diplomacy:80,strategy:95,loyalty:90,desc:"韩国贵族之后，博浪沙刺秦，后为汉初三杰。"},
  {id:"quyuan",name:"屈原",country:"楚",born:-340,died:-278,type:"文官",military:20,governance:75,diplomacy:70,strategy:60,loyalty:95,desc:"楚国三闾大夫，著《离骚》，白起拔郢后投汨罗江而死。"},
  {id:"chunshen",name:"春申君",country:"楚",born:-314,died:-238,type:"文官",military:30,governance:70,diplomacy:80,strategy:65,loyalty:75,desc:"黄歇，战国四公子之一，相楚二十余年。"},
  {id:"xiangyan",name:"项燕",country:"楚",born:-270,died:-223,type:"武将",military:85,governance:40,diplomacy:30,strategy:78,loyalty:90,desc:"楚国名将，大败秦将李信，后为王翦所败自杀。"},
  {id:"guanying",name:"管仲遗风",country:"齐",born:-400,died:-350,type:"文官",military:20,governance:80,diplomacy:65,strategy:60,loyalty:80,desc:"齐国延续管仲治国之道的贤臣。"},
  {id:"baihu",name:"白圭",country:"魏",born:-380,died:-310,type:"文官",military:10,governance:75,diplomacy:60,strategy:55,loyalty:75,desc:"商业奇才，善于经营，为魏国充实国库。"},
  {id:"gongsunyan",name:"公孙衍",country:"魏",born:-360,died:-300,type:"谋士",military:40,governance:55,diplomacy:88,strategy:80,loyalty:65,desc:"犀首，合纵运动的发起者，与张仪针锋相对。"},
  {id:"huishi",name:"惠施",country:"魏",born:-370,died:-310,type:"谋士",military:10,governance:65,diplomacy:70,strategy:75,loyalty:75,desc:"名家代表，魏相，与庄子为友。善辩，学富五车。"},
  {id:"xunzi",name:"荀子",country:"赵",born:-313,died:-238,type:"文官",military:10,governance:88,diplomacy:50,strategy:70,loyalty:80,desc:"儒家大师，三为稷下学宫祭酒，著《荀子》。"},
  {id:"mozi_legacy",name:"墨者",country:"楚",born:-350,died:-280,type:"谋士",military:50,governance:55,diplomacy:45,strategy:70,loyalty:90,desc:"墨家传人，兼爱非攻，善守城之术。"},
  {id:"jingke",name:"荆轲",country:"燕",born:-260,died:-227,type:"刺客",military:65,governance:10,diplomacy:30,strategy:40,loyalty:95,desc:"刺客，受燕太子丹之托刺秦，图穷匕见，事败身死。"},
  {id:"niezheng",name:"聂政",country:"韩",born:-410,died:-397,type:"刺客",military:70,governance:5,diplomacy:10,strategy:30,loyalty:95,desc:"刺客，为严仲子刺杀韩相侠累，自毁面容以免连累姐姐。"},
  {id:"gaoyao",name:"高要",country:"赵",born:-300,died:-250,type:"文官",military:30,governance:70,diplomacy:55,strategy:50,loyalty:80,desc:"赵国能臣，善于理财充实国库。"},
  {id:"wangben",name:"王贲",country:"秦",born:-265,died:-215,type:"武将",military:88,governance:35,diplomacy:25,strategy:80,loyalty:85,desc:"王翦之子，灭魏灭燕灭齐，秦统一功臣。"},
  {id:"neishiteng",name:"内史腾",country:"秦",born:-270,died:-220,type:"武将",military:75,governance:50,diplomacy:30,strategy:65,loyalty:80,desc:"灭韩之将，后为南郡守。"},
  {id:"tianwen",name:"田文",country:"齐",born:-320,died:-279,type:"文官",military:30,governance:65,diplomacy:82,strategy:60,loyalty:65,desc:"即孟尝君，曾入秦为相，后归齐。"},
  {id:"zhaogao",name:"赵高",country:"秦",born:-258,died:-207,type:"文官",military:15,governance:50,diplomacy:70,strategy:75,loyalty:20,desc:"秦宦官，善于逢迎，后指鹿为马。"},
  {id:"laoai",name:"嫪毐",country:"秦",born:-270,died:-238,type:"文官",military:40,governance:20,diplomacy:50,strategy:30,loyalty:15,desc:"与秦太后私通，封长信侯，后叛乱被诛。"},
  {id:"guozhong",name:"郭纵",country:"赵",born:-310,died:-260,type:"文官",military:15,governance:70,diplomacy:55,strategy:50,loyalty:75,desc:"赵国冶铁巨商，以财力助赵国军备。"},
  {id:"yueyi_son",name:"乐间",country:"燕",born:-280,died:-240,type:"武将",military:65,governance:40,diplomacy:45,strategy:60,loyalty:70,desc:"乐毅之子，后入赵为将。"},
  {id:"danyu",name:"太子丹",country:"燕",born:-255,died:-226,type:"文官",military:35,governance:40,diplomacy:60,strategy:55,loyalty:90,desc:"燕太子丹，质于秦后逃归，遣荆轲刺秦。"},
  {id:"kongfu",name:"孔斌",country:"魏",born:-300,died:-250,type:"文官",military:20,governance:78,diplomacy:55,strategy:60,loyalty:85,desc:"孔子后裔，魏相，以儒治国。"},
  {id:"xionghan",name:"熊悍",country:"楚",born:-280,died:-238,type:"武将",military:60,governance:35,diplomacy:30,strategy:55,loyalty:75,desc:"楚国宗室将领。"},
];

const ROLE_ICONS = {
  "君主": {symbol: "♛", cssClass: "icon-king"},
  "家臣": {symbol: "⌂", cssClass: "icon-vassal"},
  "文官": {symbol: "☰", cssClass: "icon-civil"},
  "武将": {symbol: "⚔", cssClass: "icon-military"},
  "谋士": {symbol: "◈", cssClass: "icon-strategist"},
  "刺客": {symbol: "†", cssClass: "icon-assassin"}
};
