const HISTORICAL_EVENTS = [
  // ═══════════════════════════════════════════════════════
  // 三家分晋纪元 (id:1) - 前403年
  // ═══════════════════════════════════════════════════════
  {id:"partition_jin",year:-403,era:[1,2],condition:{countries:["赵","魏","韩"]},title:"三家分晋",
   text:"周威烈王二十三年，天子正式册封赵籍、魏斯、韩虔为诸侯。自此，晋国名存实亡，三家各据其地。天下格局为之一变。卿以为，当如何经营新邦？",
   choices:[
     {text:"厉兵秣马，以武立国",effects:{military:18,economy:-10,governance:5},risk:0.1,chronicle:"册封为侯，以武立国"},
     {text:"修文偃武，发展经济",effects:{economy:18,military:-5,governance:10},risk:0.1,chronicle:"册封为侯，修文偃武"},
     {text:"广交诸侯，纵横捭阖",effects:{diplomacy:18,military:-5,economy:5},risk:0.1,chronicle:"册封为侯，广交诸侯"},
     {text:"内修政理，外御强敌",effects:{governance:15,military:5,morale:5},risk:0.05,chronicle:"册封为侯，内修政理"}
   ]},
  {id:"tian_replace_jiang",year:-386,era:[1,2],condition:{country:"齐"},title:"田氏代齐",
   text:"田和始列为诸侯，姜氏之齐遂为田氏之齐。田氏以大夫之身，行诸侯之事，积数世之恩，终有齐国。然姜氏旧臣多有不服。",
   choices:[
     {text:"大封功臣，安抚旧臣",effects:{governance:12,morale:10,diplomacy:5,economy:-8},risk:0.1,chronicle:"大封功臣，安抚姜氏旧臣"},
     {text:"清洗姜氏余党，以绝后患",effects:{governance:8,military:8,morale:-12},risk:0.2,chronicle:"清洗姜氏余党",
      rulerFate:{type:"被弑",chance:0.15,text:"清洗过激，姜氏死士刺杀新君",chronicle:"清洗姜氏余党，为死士所弑"}},
     {text:"推行新政，以实绩服人",effects:{governance:15,economy:10,morale:5},risk:0.1,chronicle:"推行新政，以实绩服人"}
   ]},
  {id:"wuzhi_reform_chu",year:-389,era:[1,2],condition:{country:"楚"},title:"吴起变法",
   text:"吴起自魏入楚，楚悼王用之为令尹。起欲明法审令，损不急之官，废公族疏远者，以抚养战斗之士。南平百越，北并陈蔡，却三晋，西伐秦。然楚国旧贵族恨之入骨。",
   choices:[
     {text:"全力支持吴起变法",effects:{governance:22,military:15,economy:10,morale:-15},risk:0.35,chronicle:"用吴起变法，国势大振，然贵族怨恨日深",
      rulerFate:{type:"被弑",chance:0.2,text:"贵族兵变，吴起与王同死",chronicle:"贵族兵变，吴起伏王尸而死"}},
     {text:"温和改良，循序渐进",effects:{governance:12,military:8,economy:5},risk:0.15,chronicle:"温和改良，国力渐增"},
     {text:"安抚贵族，限制变法",effects:{governance:-5,morale:10,diplomacy:5},risk:0.05,chronicle:"限制变法以安抚贵族，吴起郁郁不得志"}
   ]},
  {id:"weihuiwang",year:-369,era:[1,2],condition:{country:"魏"},title:"魏惠王争位",
   text:"魏武侯卒，子罃与公子缓争立。赵、韩助公子缓，围罃于涿泽。然赵韩不合，夜各引兵去。罃遂自立，是为惠王。",
   choices:[
     {text:"以武力统一内部，巩固王位",effects:{military:15,morale:5,governance:-5},risk:0.3,chronicle:"以武力巩固王位",
      rulerFate:{type:"战死",chance:0.2,text:"争位失败，死于乱军",chronicle:"争位失败，死于乱军之中"}},
     {text:"安抚公子缓一党，宽以待人",effects:{governance:10,morale:10,diplomacy:5},risk:0.1,chronicle:"安抚内部，宽以待人"},
     {text:"借外力压制内患",effects:{diplomacy:10,military:5,morale:-10},risk:0.2,chronicle:"借外力压制内患"}
   ]},
  {id:"yan_pianan",year:-390,era:[1,2],condition:{country:"燕"},title:"燕国偏安",
   text:"燕处北方苦寒之地，远离中原纷争。虽地广人稀，然民风淳朴，社稷安稳。朝臣有议曰：当今天下大争，燕国当何去何从？",
   choices:[
     {text:"厉兵秣马，南下争霸",effects:{military:15,economy:-10,morale:5},risk:0.15,chronicle:"燕国整军南下争霸"},
     {text:"偏安一隅，发展经济",effects:{economy:15,governance:10,military:-5},risk:0.05,chronicle:"燕国偏安发展经济"},
     {text:"北击胡人，拓展疆土",effects:{military:12,economy:8,diplomacy:5},risk:0.2,chronicle:"燕国北击胡人拓地"},
     {text:"广交齐赵，以外交自保",effects:{diplomacy:18,military:-3,morale:5},risk:0.05,chronicle:"燕国广交齐赵自保"}
   ]},

  // ═══════════════════════════════════════════════════════
  // 围魏救赵纪元 (id:2) - 前354年
  // ═══════════════════════════════════════════════════════
  {id:"qin_xiaogong_seek",year:-361,era:[1,2,3],condition:{country:"秦"},title:"秦孝公求贤令",
   text:"孝公下令国中曰：「宾客群臣有能出奇计强秦者，吾且尊官，与之分土。」卫人公孙鞅闻之，西入秦。然朝中老臣多不以为然，以为变法将动摇根基。",
   choices:[
     {text:"用商鞅行变法，废井田、重耕战",effects:{governance:22,military:18,economy:12,morale:-12},risk:0.25,chronicle:"用商鞅变法，秦国由弱转强"},
     {text:"用其才但限制其权，渐进改革",effects:{governance:12,military:8,economy:8,morale:3},risk:0.1,chronicle:"用商鞅之才而限其权，渐进改革"},
     {text:"以老臣之策为主，稳健治国",effects:{governance:5,economy:10,morale:8,military:-3},risk:0.05,chronicle:"未用商鞅，以老臣之策治国"},
     {text:"令商鞅与老臣辩论，择善而从",effects:{governance:10,diplomacy:5,military:5},risk:0.1,chronicle:"令新旧辩论，择善而从"}
   ]},
  {id:"shangyang_reform",year:-356,era:[2,3],condition:{country:"秦"},title:"商鞅变法",
   text:"卫人公孙鞅闻求贤令入秦，因嬖臣景监以求见。鞅说帝道，公寐不听；说王道，公未以为然；说霸道，公不自知膝之前于席也。鞅欲行变法以强秦，然旧族甘龙、杜挚力谏不可。",
   choices:[
     {text:"「治世不一道，便国不法古」——全力支持变法",effects:{governance:25,military:20,economy:15,morale:-15,diplomacy:-10},risk:0.35,chronicle:"用商鞅变法，废井田、重耕战、严刑峻法"},
     {text:"渐进改良，新旧兼顾",effects:{governance:12,military:8,economy:8},risk:0.1,chronicle:"渐进改良，国力有所增长"},
     {text:"驳回变法，安抚旧族",effects:{morale:10,governance:-5},risk:0.05,chronicle:"驳回变法，维持旧制"},
     {text:"用其术而不用其人",effects:{governance:15,military:10},risk:0.2,chronicle:"采商鞅之术，然未留其人"}
   ]},
  {id:"guiling_battle",year:-354,era:[1,2],condition:{countries:["赵","齐","魏"]},title:"围魏救赵·桂陵之战",
   text:"魏将庞涓围赵邯郸，城危在旦夕。齐使田忌、孙膑将兵来救。孙膑曰：「夫解杂乱纷纠者不控卷，救斗者不搏撠。批亢捣虚，形格势禁，则自为解耳。」乃引兵直趋大梁，魏果释赵而自救。",
   choices:[
     {text:"重修城防，加强军备",effects:{military:10,economy:-10,governance:5},risk:0.05,chronicle:"重修邯郸城防"},
     {text:"趁魏军回师，追击于桂陵",effects:{military:15,economy:-8},risk:0.35,chronicle:"追击魏军于桂陵"},
     {text:"遣使与魏议和，各守其地",effects:{diplomacy:10,morale:5,military:-5},risk:0.1,chronicle:"与魏议和"},
     {text:"联齐抗魏，与齐结盟",effects:{diplomacy:15,military:5},risk:0.15,chronicle:"与齐结盟抗魏"}
   ]},
  {id:"maling_battle",year:-341,era:[2,3],condition:{countries:["齐","魏"]},title:"马陵之战",
   text:"魏伐韩，齐救之。孙膑以减灶之计诱庞涓，齐军入魏地，日减其灶。庞涓大喜曰：「齐军怯，入吾地三日，士卒亡者过半。」乃弃步军，以轻骑追之。至马陵，道狭有伏兵。",
   choices:[
     {text:"依孙膑之计，设伏马陵",effects:{military:20,economy:-8,diplomacy:10},risk:0.2,chronicle:"马陵设伏，大败魏军，庞涓自刎"},
     {text:"正面决战，以力服人",effects:{military:10,economy:-15},risk:0.5,chronicle:"与魏正面决战，互有损伤"},
     {text:"围而不打，迫魏求和",effects:{diplomacy:15,military:5,economy:-5},risk:0.15,chronicle:"围魏迫和，不战而屈人之兵"}
   ]},
  {id:"shangyang_death",year:-338,era:[2,3],condition:{country:"秦"},title:"商鞅之死",
   text:"秦孝公薨，太子立，是为惠文王。公子虔之徒告商君欲反，商鞅亡命不得，终被车裂。然其所行之法，已深入秦国骨髓。卿欲如何处置？",
   choices:[
     {text:"杀商鞅而留其法",effects:{governance:10,morale:5,diplomacy:-5},risk:0.05,chronicle:"诛商鞅，然保留变法之制"},
     {text:"人法俱废，恢复旧制",effects:{governance:-15,morale:10,military:-10},risk:0.1,chronicle:"人法俱废，国力大损"},
     {text:"赦免商鞅，继续重用",effects:{governance:5,military:5,morale:-15},risk:0.4,chronicle:"赦商鞅而续用之，贵族不满",
      rulerFate:{type:"被弑",chance:0.25,text:"宗室兵变，新君被弑",chronicle:"赦商鞅激怒宗室，兵变被弑"}}
   ]},
  {id:"shenbuhai_reform",year:-355,era:[2,3],condition:{country:"韩"},title:"申不害相韩",
   text:"申不害以术说韩昭侯，昭侯用之为相。内修政教，外应诸侯，十五年，终申子之身，国治兵强，无侵韩者。",
   choices:[
     {text:"全面推行申不害之术",effects:{governance:20,military:10,diplomacy:5,morale:-5},risk:0.2,chronicle:"用申不害为相，行术治之政"},
     {text:"取其精华，去其糟粕",effects:{governance:12,military:5},risk:0.1,chronicle:"部分采纳申不害之策"},
     {text:"不用申不害，另寻治国之道",effects:{governance:-5,diplomacy:5},risk:0.05,chronicle:"未用申不害"}
   ]},
  {id:"qi_jixia",year:-350,era:[2,3],condition:{country:"齐"},title:"稷下学宫",
   text:"齐宣王好士，于稷下广招天下学者。淳于髡、邹衍、田骈等七十六人皆赐列第，为上大夫。不治而议论，著书言治乱之事。然养士耗费巨大，朝中颇有微词。",
   choices:[
     {text:"大力扩建稷下学宫，广纳百家",effects:{governance:12,diplomacy:15,economy:-12,morale:8},risk:0.05,chronicle:"扩建稷下学宫，百家争鸣"},
     {text:"维持现状，不扩不缩",effects:{governance:5,diplomacy:5},risk:0.0,chronicle:"维持稷下学宫现状"},
     {text:"裁减学宫规模，节省国用",effects:{economy:10,governance:-5,diplomacy:-8,morale:-5},risk:0.05,chronicle:"裁减稷下学宫，学者散去"}
   ]},
  {id:"zhao_tuqiang",year:-350,era:[2],condition:{country:"赵"},title:"赵国图强",
   text:"桂陵之战后，赵国虽保邯郸，然国力大损。朝臣议论纷纷：有人主张休养生息，有人主张厉兵秣马以报魏仇，亦有人主张南联韩魏、北抗胡人。",
   choices:[
     {text:"休养生息，恢复国力",effects:{economy:15,morale:12,military:-5},risk:0.05,chronicle:"赵国休养生息"},
     {text:"厉兵秣马，以报魏仇",effects:{military:18,economy:-12,morale:8},risk:0.15,chronicle:"赵国厉兵秣马备战"},
     {text:"南联韩魏，共抗强齐",effects:{diplomacy:15,military:5,economy:-5},risk:0.1,chronicle:"赵国联韩魏抗齐"},
     {text:"北击中山，拓展疆土",effects:{military:12,economy:8,diplomacy:-5},risk:0.2,chronicle:"赵国北击中山拓地",territoryEffect:{gain:true,from:"燕"}}
   ]},
  {id:"chu_nankuo",year:-360,era:[2],condition:{country:"楚"},title:"楚国南扩",
   text:"吴起变法虽废，然楚国军力犹存。南方百越之地广袤无垠，若能征服，可得千里之地、百万之民。然南方瘴疠之地，士卒多病，且贵族内斗未息。",
   choices:[
     {text:"南征百越，拓展疆土",effects:{military:12,economy:10,diplomacy:-5},risk:0.25,chronicle:"楚国南征百越"},
     {text:"先安内政，再图外扩",effects:{governance:15,morale:8,economy:5},risk:0.1,chronicle:"楚国先安内政"},
     {text:"北图中原，与三晋争锋",effects:{military:15,diplomacy:-10,economy:-8},risk:0.3,chronicle:"楚国北图中原"},
     {text:"东联齐国，共抗秦魏",effects:{diplomacy:15,military:5,economy:3},risk:0.1,chronicle:"楚国东联齐国"}
   ]},
  {id:"yan_neizheng",year:-350,era:[2],condition:{country:"燕"},title:"燕国内政",
   text:"燕国地处北疆，与齐赵为邻。齐国田氏代齐后国势日盛，赵国桂陵之战后亦在恢复。燕国夹在两大之间，朝臣有主战者，有主和者，亦有主张变法自强者。",
   choices:[
     {text:"变法自强，效仿秦国",effects:{governance:18,military:10,morale:-8},risk:0.2,chronicle:"燕国变法自强"},
     {text:"联齐抗赵，以外交自保",effects:{diplomacy:15,military:-5,economy:5},risk:0.1,chronicle:"燕国联齐抗赵"},
     {text:"联赵抗齐，远交近攻",effects:{diplomacy:12,military:8,economy:-5},risk:0.15,chronicle:"燕国联赵抗齐"},
     {text:"闭关自守，不问世事",effects:{economy:10,morale:8,diplomacy:-10},risk:0.05,chronicle:"燕国闭关自守"}
   ]},

  // ═══════════════════════════════════════════════════════
  // 合纵连横纪元 (id:3) - 前318年
  // ═══════════════════════════════════════════════════════
  {id:"qin_zhangyi",year:-328,era:[3,4],condition:{country:"秦"},title:"张仪连横",
   text:"张仪入秦，说秦王曰：「合纵者，苏秦之遗策也。六国各怀鬼胎，不可久合。臣请以连横破之。」然连横之策需远交近攻，耗费巨大。",
   choices:[
     {text:"用张仪连横之策，远交近攻",effects:{diplomacy:18,military:8,economy:-10,governance:5},risk:0.15,chronicle:"用张仪连横之策"},
     {text:"连横太险，不如先修内政",effects:{governance:12,economy:10,diplomacy:-5},risk:0.05,chronicle:"未用连横，先修内政"},
     {text:"用张仪但暗中监视，防其卖国",effects:{diplomacy:12,governance:5,military:3},risk:0.2,chronicle:"用张仪而暗中监视"}
   ]},
  {id:"qin_simacuo_shu",year:-316,era:[3,4],condition:{country:"秦"},title:"伐蜀之议",
   text:"蜀国内乱，司马错请伐蜀。张仪反对，以为不如伐韩以逼周天子。司马错曰：「欲富国者务广其地，欲强兵者务富其民。蜀，西僻之国也，取其地足以广国，得其财足以富民。」",
   choices:[
     {text:"从司马错之策，伐蜀取地",effects:{economy:18,military:8,governance:5,diplomacy:-5},risk:0.2,chronicle:"伐蜀成功，得巴蜀粮仓",territoryEffect:{gain:true,from:"楚"}},
     {text:"从张仪之策，伐韩逼周",effects:{military:12,diplomacy:10,economy:-8},risk:0.3,chronicle:"伐韩逼周，得九鼎之威"},
     {text:"两策并用，先取蜀再图韩",effects:{economy:12,military:5,governance:3},risk:0.15,chronicle:"先取蜀地，再图东进"}
   ]},
  {id:"hezong_attack_qin",year:-318,era:[3,4],condition:{countries:["赵","魏","韩","楚","燕"]},title:"五国合纵攻秦",
   text:"苏秦之遗策，公孙衍发起五国合纵攻秦。赵、魏、韩、楚、燕联军西进，兵至函谷关。然各国心怀鬼胎，貌合神离。秦据关而守，联军进退维谷。",
   choices:[
     {text:"全力攻秦，不惜代价",effects:{military:15,economy:-20,diplomacy:10},risk:0.6,chronicle:"全力攻秦，然函谷天险难破"},
     {text:"虚张声势，各保疆土",effects:{diplomacy:5,military:-5,morale:5},risk:0.1,chronicle:"合纵虚张声势，各保疆土"},
     {text:"趁合纵之势，攻取邻国边城",effects:{military:10,diplomacy:-15,economy:5},risk:0.3,chronicle:"趁合纵之机，攻取邻国边城"},
     {text:"暗通秦国，出卖联军",effects:{diplomacy:-20,military:5,economy:10},risk:0.4,chronicle:"暗通秦国，出卖联军"}
   ]},
  {id:"hufu_qishe",year:-306,era:[3,4],condition:{country:"赵"},title:"胡服骑射",
   text:"赵武灵王欲胡服骑射以教百姓。肥义曰：「王毋忧，臣请为王先行。」公子成等宗室大臣皆不从，曰：「中国者，圣贤之所教也，礼乐之所用也。今王舍此而袭远方之服，变古之教，易古之道，逆人之心。」",
   choices:[
     {text:"力排众议，全面推行胡服骑射",effects:{military:25,economy:5,morale:-10,governance:10},risk:0.25,chronicle:"推行胡服骑射，赵军骑兵冠绝天下"},
     {text:"先在军中推行，民间自愿",effects:{military:15,economy:3,morale:5},risk:0.1,chronicle:"军中先行胡服骑射"},
     {text:"放弃改革，维持旧制",effects:{morale:10,military:-5},risk:0.05,chronicle:"放弃胡服骑射之议"}
   ]},
  {id:"yan_zhao_wang",year:-311,era:[3,4],condition:{country:"燕"},title:"燕昭王筑黄金台",
   text:"燕昭王即位，卑身厚币以招贤者。谓郭隗曰：「齐因孤之国乱而袭破燕，孤极知燕小力少，不足以报。然诚得贤士以共国，以雪先人之耻。」隗曰：「王必欲致士，先从隗始。况贤于隗者，岂远千里哉！」",
   choices:[
     {text:"筑黄金台，广招天下贤才",effects:{governance:20,diplomacy:15,economy:-10,military:10},risk:0.05,chronicle:"筑黄金台，乐毅、邹衍等贤才纷至"},
     {text:"只招军事人才，以报齐仇",effects:{military:15,diplomacy:-5},risk:0.1,chronicle:"专招军事人才，矢志报仇"},
     {text:"内修政理，不急于报仇",effects:{governance:15,economy:10,morale:5},risk:0.05,chronicle:"内修政理，暂缓报仇之议"}
   ]},
  {id:"chu_quyuan",year:-305,era:[3,4],condition:{country:"楚"},title:"屈原之谏",
   text:"屈原为楚怀王左徒，博闻强志，明于治乱，娴于辞令。入则与王图议国事，出则接遇宾客。然上官大夫靳尚嫉之，数谗于王。后宫郑袖亦受张仪之赂，日夜言屈原之短。",
   choices:[
     {text:"信任屈原，斥退靳尚与郑袖",effects:{governance:15,diplomacy:10,morale:10,economy:-5},risk:0.15,chronicle:"信任屈原，斥退谗臣"},
     {text:"两不相帮，维持朝堂平衡",effects:{governance:-3,morale:-3,diplomacy:3},risk:0.05,chronicle:"未置可否，朝堂纷争不断"},
     {text:"听信靳尚，疏远屈原",effects:{governance:-10,diplomacy:-10,morale:-5},risk:0.1,chronicle:"疏远屈原，朝政日非"}
   ]},
  {id:"han_guiling2",year:-310,era:[3],condition:{country:"韩"},title:"韩国夹缝求生",
   text:"韩国地处天下之枢，四面皆强邻。秦欲东进，必先取韩；魏欲南扩，亦窥韩地。韩国虽小，然冶铁之术冠绝天下，强弩之利为诸侯所畏。当此存亡之际，卿将如何？",
   choices:[
     {text:"事秦以求自保",effects:{diplomacy:12,military:-8,morale:-10},risk:0.15,chronicle:"韩国事秦求存"},
     {text:"合纵抗秦，联赵魏自保",effects:{diplomacy:15,military:8,economy:-8},risk:0.25,chronicle:"韩国合纵抗秦"},
     {text:"发展冶铁强弩，以武自保",effects:{military:18,economy:10,diplomacy:-5},risk:0.1,chronicle:"韩国发展冶铁强弩"},
     {text:"以外交周旋于列强之间",effects:{diplomacy:20,economy:5,military:-5},risk:0.2,chronicle:"韩国以外交周旋"}
   ]},

  // ═══════════════════════════════════════════════════════
  // 白起拔郢纪元 (id:4) - 前278年
  // ═══════════════════════════════════════════════════════
  {id:"yueyi_attack_qi",year:-284,era:[3,4,5],condition:{countries:["燕","齐"],contextCountry:"燕",contextMinMilitary:35},title:"乐毅伐齐",
   text:"燕昭王二十八年，乐毅率燕、秦、赵、魏、韩五国联军伐齐。济西大败齐师，乐毅独率燕军长驱直入，下齐七十余城，唯莒、即墨未下。齐湣王走莒。",
   choices:[
     {text:"继续围攻莒、即墨，务求全灭齐国",effects:{military:15,economy:-15,morale:5},risk:0.5,chronicle:"继续围攻齐国残余"},
     {text:"以德服人，安抚齐民",effects:{governance:15,diplomacy:10,military:-5},risk:0.2,chronicle:"安抚齐民，以德怀远"},
     {text:"见好就收，携胜果议和",effects:{diplomacy:15,economy:10,military:5},risk:0.1,chronicle:"携大胜之威与齐议和"}
   ]},
  {id:"tianjin_restore_qi",year:-279,era:[3,4,5],condition:{country:"齐"},title:"火牛复齐",
   text:"田单以即墨一城抗燕数年。乃收城中牛千余头，画以五彩龙文，角缚利刃，尾束苇灌脂。夜凿城数十穴，纵牛出，壮士五千随后。牛尾炬火，光明炫耀，燕军大骇，齐人乘胜追击。",
   choices:[
     {text:"依田单之计，火牛阵出击",effects:{military:25,morale:20,economy:-10},risk:0.3,chronicle:"火牛阵大破燕军，收复七十余城"},
     {text:"继续坚守，等待外援",effects:{military:5,morale:-5,economy:-8},risk:0.4,chronicle:"坚守即墨，苦待外援"},
     {text:"与燕议和，保全即墨",effects:{diplomacy:10,military:-10,morale:-10},risk:0.1,chronicle:"与燕议和，仅保即墨一城"}
   ]},
  {id:"baiqi_ying",year:-278,era:[4,5],condition:{countries:["秦","楚"],contextCountry:"秦",contextMinMilitary:30},title:"白起拔郢",
   text:"秦将白起率军攻楚，决水淹鄢，军民死者数十万。遂拔郢都，烧夷陵，东至竟陵。楚王亡走陈，东迁于寿春。屈原闻之，怀石投汨罗江而死。",
   choices:[
     {text:"乘胜追击，务求灭楚",effects:{military:20,economy:-15,diplomacy:-10},risk:0.4,chronicle:"乘胜追击楚军"},
     {text:"巩固新地，设南郡而治",effects:{governance:15,economy:10,military:5},risk:0.1,chronicle:"设南郡，巩固楚地"},
     {text:"与楚议和，割地而还",effects:{diplomacy:15,economy:5,military:-5},risk:0.1,chronicle:"与楚议和，割地而还"}
   ]},
  {id:"chu_huaiwang",year:-299,era:[3,4,5],condition:{country:"楚"},title:"楚怀王入秦",
   text:"秦昭王遗书楚怀王曰：「寡人与王接境，婚姻也。愿与王会武关，面相约而去。」屈原谏曰：「秦，虎狼之国，不可信。」子兰劝王行。王入秦，秦因留之。",
   choices:[
     {text:"听从屈原，拒绝入秦",effects:{diplomacy:-5,governance:10,morale:10},risk:0.1,chronicle:"拒绝入秦，保全自身"},
     {text:"入秦赴会，以示诚信",effects:{diplomacy:5,military:-20,morale:-15},risk:0.8,chronicle:"入秦被扣，楚国大乱",
      rulerFate:{type:"被掳",chance:0.7,text:"入秦被扣，客死他乡",chronicle:"楚怀王入秦被扣，终客死于秦"}},
     {text:"带重兵护卫前往",effects:{diplomacy:0,military:-5,economy:-8},risk:0.4,chronicle:"带兵赴会，秦不敢轻动",
      rulerFate:{type:"被掳",chance:0.3,text:"秦军伏兵，楚王被掳",chronicle:"秦设伏兵，楚王虽带兵仍被掳"}}
   ]},
  {id:"fanju_yuanjiao",year:-270,era:[4,5],condition:{country:"秦",contextCountry:"秦",contextMinMilitary:25},title:"范雎远交近攻",
   text:"范雎说秦王曰：「夫韩、魏，中国之处而天下之枢也。王欲霸，必亲中国以为天下枢。不如远交而近攻，得寸则王之寸，得尺则王之尺也。」",
   choices:[
     {text:"采纳远交近攻之策",effects:{diplomacy:20,military:10,governance:10},risk:0.05,chronicle:"采纳远交近攻之策，战略更加清晰"},
     {text:"继续四面出击",effects:{military:5,diplomacy:-10},risk:0.2,chronicle:"未采纳远交近攻，继续四面出击"},
     {text:"只取近攻，不事远交",effects:{military:10,diplomacy:-5},risk:0.15,chronicle:"只行近攻之策"}
   ]},
  {id:"han_kunjin",year:-275,era:[4,5],condition:{country:"韩"},title:"韩国的困境",
   text:"秦军屡伐韩国，攻城略地。韩国地狭兵弱，难以独抗强秦。朝中有人主张割地求和以延国祚，有人主张联赵抗秦以图存，亦有人主张举国东迁以避秦锋。",
   choices:[
     {text:"割地求和，以延国祚",effects:{diplomacy:8,morale:-15,military:-8},risk:0.15,chronicle:"韩国割地求和"},
     {text:"联赵抗秦，合纵图存",effects:{diplomacy:15,military:10,economy:-10},risk:0.3,chronicle:"韩国联赵抗秦"},
     {text:"发展冶铁强弩，死守国境",effects:{military:15,economy:-8,morale:8},risk:0.25,chronicle:"韩国死守国境"},
     {text:"向秦称臣，保全宗庙",effects:{diplomacy:5,morale:-20,military:-12},risk:0.1,chronicle:"韩国向秦称臣",
      rulerFate:{type:"被掳",chance:0.2,text:"秦不受降，仍被掳去",chronicle:"虽称臣仍被秦所掳"}}
   ]},
  {id:"wei_xinling2",year:-275,era:[4,5],condition:{country:"魏"},title:"信陵君养士",
   text:"信陵君魏无忌，仁而下士，食客三千。天下士人闻风而至。然魏王忌之，不敢委以国政。信陵君虽有救赵之功，却不得重用。",
   choices:[
     {text:"委信陵君以国政，共图大业",effects:{governance:15,diplomacy:12,military:10,morale:8},risk:0.15,chronicle:"委信陵君以国政"},
     {text:"令信陵君守边，远离朝堂",effects:{military:12,governance:-5,morale:-5},risk:0.1,chronicle:"令信陵君守边"},
     {text:"猜忌信陵君，削其兵权",effects:{governance:5,military:-10,morale:-8},risk:0.2,chronicle:"猜忌信陵君，削其兵权"}
   ]},

  // ═══════════════════════════════════════════════════════
  // 长平决战纪元 (id:5) - 前260年
  // ═══════════════════════════════════════════════════════
  {id:"changping_battle",year:-260,era:[4,5],condition:{countries:["秦","赵"]},title:"长平之战",
   text:"秦攻韩上党，上党守冯亭不降秦，反以上党十七城归赵。秦怒，遣武安君白起攻赵于长平。廉颇坚壁不出，秦人不得进。然旷日持久，粮草渐匮。秦使反间曰：「秦之所畏，独赵括耳。」",
   choices:[
     {text:"信廉颇之策，继续坚守",effects:{military:10,economy:-15,morale:5},risk:0.3,chronicle:"廉颇坚守长平，秦军久攻不下"},
     {text:"以赵括代廉颇，主动出击",effects:{military:-30,morale:-20,economy:-10},risk:0.85,chronicle:"赵括代廉颇出击，大败于长平，损兵四十余万",
      rulerFate:{type:"被掳",chance:0.4,text:"长平大败，赵王被秦军所掳",chronicle:"长平大败，赵王被掳于秦"}},
     {text:"遣使求和于秦",effects:{diplomacy:10,military:-10,morale:-5},risk:0.3,chronicle:"遣使求和于秦"},
     {text:"暗联魏楚，请出兵夹击",effects:{diplomacy:15,military:5,economy:-8},risk:0.4,chronicle:"联魏楚夹击秦军"}
   ]},
  {id:"xinling_save_zhao",year:-257,era:[4,5],condition:{countries:["魏","赵"]},title:"窃符救赵",
   text:"长平之后，秦围邯郸。赵使平原君求救于魏。魏王使晋鄙将十万众救赵，然畏秦，驻兵不进。信陵君魏无忌欲救赵，侯嬴献窃符之计。",
   choices:[
     {text:"窃符夺军，救赵抗秦",effects:{military:15,diplomacy:20,morale:10,governance:-10},risk:0.35,chronicle:"窃符救赵，大破秦军于邯郸城下"},
     {text:"遵从王命，按兵不动",effects:{diplomacy:-15,morale:-10,military:5},risk:0.1,chronicle:"按兵不动，坐视赵国危亡"},
     {text:"劝魏王亲自下令救赵",effects:{diplomacy:10,military:5,morale:5},risk:0.3,chronicle:"力谏魏王救赵"}
   ]},
  {id:"jingke_assassination",year:-227,era:[5,6],condition:{country:"燕"},title:"荆轲刺秦",
   text:"太子丹质于秦，秦王遇之不善，丹亡归。欲报秦仇，得刺客荆轲。以秦舞阳为副，携樊於期之首、督亢之图，入秦献之。图穷匕见，事败身死。",
   choices:[
     {text:"遣荆轲入秦，行刺秦王",effects:{diplomacy:-25,military:-5,morale:10},risk:0.8,chronicle:"遣荆轲刺秦，事败，秦大怒",
      rulerFate:{type:"被掳",chance:0.5,text:"秦军大举攻燕，燕王被掳",chronicle:"刺秦失败，秦军大举攻燕，燕王被掳"}},
     {text:"放弃刺杀，整军备战",effects:{military:15,economy:-10,morale:5},risk:0.2,chronicle:"放弃刺杀，整军备战"},
     {text:"遣使入秦求和，献地称臣",effects:{diplomacy:10,morale:-15,military:-10},risk:0.15,chronicle:"遣使求和，献地称臣"}
   ]},
  {id:"qin_destroy_han",year:-230,era:[5,6],condition:{country:"韩"},title:"秦灭韩",
   text:"秦王政十七年，内史腾率军攻韩，虏韩王安，尽取其地，置颍川郡。韩亡，为六国中第一个被灭者。",
   choices:[
     {text:"举国抵抗，死战到底",effects:{military:10,morale:15,economy:-20},risk:0.7,chronicle:"举国抵抗秦军",
      rulerFate:{type:"战死",chance:0.5,text:"兵败身死",chronicle:"抵抗失败，韩王战死"}},
     {text:"遣使求和，割地称臣",effects:{diplomacy:5,morale:-20,military:-10},risk:0.3,chronicle:"割地求和，苟延残喘"},
     {text:"联赵抗秦，合纵自保",effects:{diplomacy:15,military:5,economy:-8},risk:0.5,chronicle:"联赵抗秦"}
   ]},
  {id:"limu_defeat_qin",year:-233,era:[5,6],condition:{country:"赵"},title:"李牧却秦",
   text:"秦攻赵，李牧率师与战于肥下，大败秦军。赵王封李牧为武安君。后秦又攻赵，李牧与战番吾，复败秦军。秦人闻李牧在，不敢轻犯。",
   choices:[
     {text:"重用李牧，委以全国兵权",effects:{military:20,morale:15,governance:5},risk:0.1,chronicle:"重用李牧，秦军不敢犯境"},
     {text:"李牧功高震主，须加防范",effects:{military:5,morale:-10,governance:5},risk:0.3,chronicle:"猜忌李牧，君臣生隙"},
     {text:"让李牧训练新军，扩大战果",effects:{military:15,economy:-10},risk:0.15,chronicle:"命李牧扩军备战"}
   ]},
  {id:"qin_unification_start",year:-230,era:[5,6],condition:{countries:["秦","赵","齐","楚","燕","魏"],contextCountry:"秦",contextMinMilitary:40},title:"秦灭六国之始",
   text:"秦王政十七年，内史腾灭韩。自此，秦以摧枯拉朽之势，逐一吞并六国。天下大势，已不可逆转。",
   choices:[
     {text:"联合残余诸国，拼死一搏",effects:{military:15,diplomacy:10,economy:-15,morale:10},risk:0.6,chronicle:"联合诸国残余，拼死抗秦",
      rulerFate:{type:"战死",chance:0.35,text:"抗秦失败，战死沙场",chronicle:"联合抗秦失败，战死沙场"}},
     {text:"向秦称臣，保全宗庙",effects:{diplomacy:5,morale:-25,military:-15},risk:0.2,chronicle:"向秦称臣"},
     {text:"整顿内政，以逸待劳",effects:{governance:10,economy:10,military:5},risk:0.3,chronicle:"整顿内政，以逸待劳"}
   ]},
  {id:"qin_lubuwei",year:-249,era:[5,6],condition:{country:"秦"},title:"吕不韦奇货可居",
   text:"吕不韦以商人之身，助质子异人归秦即位。不韦官至丞相，号称「仲父」。然其权倾朝野，与太后私通，门客三千。王年渐长，当如何处置？",
   choices:[
     {text:"逐步收回权柄，令吕不韦致仕",effects:{governance:15,morale:8,diplomacy:-5},risk:0.2,chronicle:"逐步收回吕不韦之权"},
     {text:"信任仲父，委以国政",effects:{governance:5,economy:10,diplomacy:8,morale:-8},risk:0.15,chronicle:"信任吕不韦，委以国政",
      rulerFate:{type:"被架空",chance:0.2,text:"吕不韦权倾朝野，王被架空",chronicle:"吕不韦专权，秦王被架空，被迫退位"}},
     {text:"以雷霆手段诛杀吕不韦",effects:{governance:10,military:5,morale:5,economy:-10},risk:0.3,chronicle:"诛杀吕不韦，朝野震动",
      rulerFate:{type:"被弑",chance:0.2,text:"诛吕不成，反被其害",chronicle:"诛吕不韦不成，反被其党羽所弑"}},
     {text:"利用吕不韦之才，但暗中培植自己的势力",effects:{governance:12,diplomacy:5,military:5},risk:0.1,chronicle:"利用吕不韦之才，暗中培植势力"}
   ]},
  {id:"qi_laststand",year:-240,era:[5,6],condition:{country:"齐"},title:"齐国的抉择",
   text:"秦灭韩、赵之后，兵锋直指东方。齐国四十余年不修兵革，临淄虽富，然军备废弛。秦使来朝，以利害说齐王。朝中主战主降，各执一词。",
   choices:[
     {text:"整军备战，死守临淄",effects:{military:15,morale:12,economy:-15},risk:0.5,chronicle:"齐国整军备战",
      rulerFate:{type:"战死",chance:0.3,text:"秦军攻破临淄，齐王战死",chronicle:"秦军攻破临淄，齐王战死"}},
     {text:"联楚抗秦，合纵自保",effects:{diplomacy:15,military:8,economy:-8},risk:0.35,chronicle:"齐国联楚抗秦"},
     {text:"向秦称臣，保全社稷",effects:{diplomacy:5,morale:-20,military:-12},risk:0.15,chronicle:"齐国向秦称臣"},
     {text:"西行入秦，以求封侯",effects:{diplomacy:8,morale:-15,governance:-5},risk:0.25,chronicle:"齐王入秦",
      rulerFate:{type:"被掳",chance:0.4,text:"入秦后被扣留",chronicle:"齐王入秦后被扣留，客死他乡"}}
   ]},
  {id:"chu_laststand",year:-240,era:[5,6],condition:{country:"楚"},title:"楚国的最后防线",
   text:"秦军屡伐楚国，失郢都、丧夷陵，楚国已退至寿春。项燕虽勇，然秦军势如破竹。楚王当如何抉择？是战是降，社稷存亡在此一举。",
   choices:[
     {text:"命项燕率军死战，誓保社稷",effects:{military:18,morale:15,economy:-15},risk:0.45,chronicle:"楚国命项燕死战",
      rulerFate:{type:"战死",chance:0.35,text:"项燕兵败，楚王被掳",chronicle:"项燕兵败，楚王被秦军所掳"}},
     {text:"联齐燕抗秦，合纵图存",effects:{diplomacy:15,military:8,economy:-8},risk:0.3,chronicle:"楚国合纵抗秦"},
     {text:"南迁百越之地，保存实力",effects:{economy:8,military:-5,morale:-10},risk:0.15,chronicle:"楚国南迁百越"},
     {text:"向秦求和，割地称臣",effects:{diplomacy:5,morale:-18,military:-10},risk:0.2,chronicle:"楚国割地求和"}
   ]},

  // ═══════════════════════════════════════════════════════
  // 秦灭六国纪元 (id:6) - 前230年
  // ═══════════════════════════════════════════════════════
  {id:"wangjian_destroy_zhao",year:-228,era:[6],condition:{country:"赵"},title:"王翦灭赵",
   text:"秦王政十九年，王翦率大军攻赵。赵有李牧，秦以反间计除之。赵军无将，遂大败。王翦攻破邯郸，虏赵王迁。赵国公子嘉北走代地，自立为代王。",
   choices:[
     {text:"死守邯郸，与城共存亡",effects:{military:12,morale:18,economy:-20},risk:0.65,chronicle:"死守邯郸",
      rulerFate:{type:"被掳",chance:0.5,text:"城破被掳",chronicle:"邯郸城破，赵王被掳至咸阳"}},
     {text:"弃邯郸北走代地，保存赵祀",effects:{military:-8,morale:-12,economy:5},risk:0.3,chronicle:"北走代地"},
     {text:"遣使求和，割地称臣",effects:{diplomacy:5,morale:-20,military:-12},risk:0.2,chronicle:"割地求和于秦"}
   ]},
  {id:"wangben_destroy_wei",year:-225,era:[6],condition:{country:"魏"},title:"王贲水淹大梁",
   text:"秦王政二十二年，王贲率军攻魏，引黄河水灌大梁城。大梁城墙崩塌，魏王假出降。魏国遂亡。",
   choices:[
     {text:"死守大梁，死战到底",effects:{military:10,morale:15,economy:-15},risk:0.7,chronicle:"死守大梁",
      rulerFate:{type:"被掳",chance:0.6,text:"大梁城破，魏王被掳",chronicle:"大梁城破，魏王被掳于秦"}},
     {text:"弃城突围，投奔齐国",effects:{military:-10,morale:-15,diplomacy:5},risk:0.4,chronicle:"弃大梁投齐"},
     {text:"开城投降，保全百姓",effects:{diplomacy:3,morale:-18,military:-15},risk:0.1,chronicle:"开城投降"},
     {text:"联楚抗秦，做最后一搏",effects:{diplomacy:12,military:8,economy:-10},risk:0.5,chronicle:"联楚最后抗秦"}
   ]},
  {id:"wangjian_destroy_chu",year:-223,era:[6],condition:{country:"楚"},title:"王翦灭楚",
   text:"秦王政二十四年，王翦率六十万大军伐楚。楚将项燕虽勇，然大势已去。秦军破楚，虏楚王负刍。项燕兵败自杀。",
   choices:[
     {text:"命项燕死战，守卫社稷",effects:{military:15,morale:15,economy:-18},risk:0.55,chronicle:"命项燕死战",
      rulerFate:{type:"被掳",chance:0.45,text:"项燕兵败，楚王被掳",chronicle:"项燕兵败，楚王被掳"}},
     {text:"南迁百越，经营后方",effects:{economy:8,military:-8,morale:-10},risk:0.25,chronicle:"楚国南迁百越"},
     {text:"向秦屈服，割地称臣",effects:{diplomacy:5,morale:-20,military:-10},risk:0.15,chronicle:"楚国割地求和"},
     {text:"散尽国库犒军，激励士气",effects:{military:10,economy:-12,morale:12},risk:0.35,chronicle:"散国库犒军"}
   ]},
  {id:"wangben_destroy_yan",year:-222,era:[6],condition:{country:"燕"},title:"王贲灭燕",
   text:"秦王政二十五年，王贲攻燕辽东，虏燕王喜。燕太子丹虽遣荆轲刺秦，然终不能挽狂澜于既倒。燕国遂亡。",
   choices:[
     {text:"死守辽东，至死不降",effects:{military:10,morale:15,economy:-10},risk:0.6,chronicle:"死守辽东",
      rulerFate:{type:"被掳",chance:0.5,text:"燕王被掳",chronicle:"秦军攻破辽东，燕王被掳"}},
     {text:"东渡入朝鲜，另立新国",effects:{economy:5,morale:-10,military:-5},risk:0.35,chronicle:"东渡朝鲜"},
     {text:"向秦献太子丹之首，以求和",effects:{diplomacy:3,morale:-18,military:-5},risk:0.15,chronicle:"献太子丹之首求和"},
     {text:"联合代王嘉，共抗秦军",effects:{diplomacy:12,military:8,economy:-8},risk:0.4,chronicle:"联代王嘉抗秦"}
   ]},
  {id:"wangben_destroy_qi",year:-221,era:[6],condition:{country:"齐"},title:"王贲灭齐",
   text:"秦王政二十六年，王贲自燕南攻齐，如入无人之境。齐国四十余年不修兵革，临淄虽富，却无将无兵。齐王建出降，齐国遂亡。",
   choices:[
     {text:"整军备战，死守临淄",effects:{military:12,morale:12,economy:-15},risk:0.55,chronicle:"死守临淄",
      rulerFate:{type:"被掳",chance:0.4,text:"临淄城破，齐王被掳",chronicle:"临淄城破，齐王被掳于秦"}},
     {text:"举国投降，保全百姓",effects:{diplomacy:5,morale:-20,military:-15},risk:0.1,chronicle:"举国投降",
      rulerFate:{type:"被掳",chance:0.5,text:"出降后遭秦王流放",chronicle:"齐王出降，遭秦王流放饿死"}},
     {text:"联楚抗秦，做最后挣扎",effects:{diplomacy:10,military:8,economy:-10},risk:0.5,chronicle:"联楚最后抗秦"},
     {text:"散尽国库以充军需",effects:{military:12,economy:-20,morale:8},risk:0.3,chronicle:"散国库充军需"}
   ]},
  {id:"qin_unification",year:-221,era:[6],condition:{countries:["秦","赵","齐","楚","燕","魏","韩"]},title:"天下一统",
   text:"六国皆灭，四海归一。秦王政号曰始皇帝，分天下为三十六郡，统一度量衡、书同文、车同轨。一个崭新的时代即将开启。当此历史转折之际，卿将如何迎接新时代？",
   choices:[
     {text:"顺应天命，归顺大秦",effects:{governance:10,morale:8,diplomacy:15},risk:0.0,chronicle:"归顺大秦"},
     {text:"解甲归田，隐于山林",effects:{morale:12,governance:5,military:-10},risk:0.0,chronicle:"隐于山林"},
     {text:"东山再起，图谋复国",effects:{military:8,morale:10,diplomacy:-15},risk:0.4,chronicle:"图谋复国",
      rulerFate:{type:"被掳",chance:0.5,text:"复国图谋败露，被秦所执",chronicle:"图谋复国败露，被秦所执"}},
     {text:"以身殉国，不事二主",effects:{military:5,morale:15,governance:-15},risk:0.0,chronicle:"以身殉国",
      rulerFate:{type:"殉国",chance:1.0,text:"以身殉国",chronicle:"国亡，以身殉国"}}
   ]},

  // ═══════════════════════════════════════════════════════
  // 通用历史事件（多国共享，跨纪元）— 使游戏内容充实
  // ═══════════════════════════════════════════════════════
  {id:"shared_diplomatic_crisis",year:-380,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"列国外交危机",
   text:"邻国与远方大国结盟，对我形成犄角之势。朝臣议论纷纷：有人主张瓦解对方同盟，有人主张寻求新的盟友，亦有人主张先发制人以打破包围。",
   choices:[
     {text:"遣使离间，瓦解敌方同盟",effects:{diplomacy:15,military:-3,economy:-5},risk:0.2,chronicle:"遣使离间敌方同盟"},
     {text:"拉拢远方大国，形成反包围",effects:{diplomacy:12,economy:-8,military:3},risk:0.15,chronicle:"拉拢远方大国"},
     {text:"先发制人，出兵打破包围",effects:{military:12,diplomacy:-15,economy:-10},risk:0.35,chronicle:"先发制人出兵"},
     {text:"示弱于敌，暗中整军备战",effects:{military:8,diplomacy:5,morale:-3},risk:0.1,chronicle:"示弱于敌，暗中备战"}
   ]},
  {id:"shared_war_rumor",year:-360,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"边境风声鹤唳",
   text:"探马报：邻国在边境集结重兵，似有犯境之意。群臣议论纷纷，有请战者，有主和者，亦有主张固守者。实情如何，尚无确凿证据。",
   choices:[
     {text:"集结大军，对峙边境",effects:{military:12,economy:-10,diplomacy:-5},risk:0.2,chronicle:"集结大军对峙边境"},
     {text:"遣使询问，表明善意",effects:{diplomacy:12,military:-3,morale:5},risk:0.1,chronicle:"遣使询问边境事宜"},
     {text:"加固边防，以静制动",effects:{military:8,governance:5,economy:-3},risk:0.05,chronicle:"加固边防以静制动"},
     {text:"佯装不知，暗中布置伏兵",effects:{military:10,diplomacy:5,governance:-3},risk:0.25,chronicle:"暗中布置伏兵"}
   ]},
  {id:"shared_trade_dispute",year:-340,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"商路之争",
   text:"我国商旅在邻国边境被扣押，货物被没收。商人联名上书请朝廷做主。对方声称我商旅违反当地法令。此事若处理不当，恐引发冲突。",
   choices:[
     {text:"遣使严正交涉，要求赔偿",effects:{diplomacy:8,morale:8,economy:5},risk:0.15,chronicle:"遣使严正交涉商旅之事"},
     {text:"直接报复，扣押对方商人",effects:{economy:10,diplomacy:-12,morale:3},risk:0.25,chronicle:"以牙还牙扣押对方商人"},
     {text:"息事宁人，安抚本国商人",effects:{economy:-5,morale:-5,diplomacy:3},risk:0.05,chronicle:"息事宁人安抚商人"},
     {text:"借此机会重启双边贸易谈判",effects:{diplomacy:12,economy:8,governance:5},risk:0.1,chronicle:"借机重启贸易谈判"}
   ]},
  {id:"shared_reform_debate",year:-320,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"变法之议",
   text:"朝中新锐大臣上疏，痛陈旧制弊端，主张全面变革以强国。然老臣一片反对之声，以为祖宗之法不可轻易变动。朝堂之上，新旧两派争执不休。",
   choices:[
     {text:"支持变法，乾坤再造",effects:{governance:18,military:12,morale:-10,diplomacy:3},risk:0.25,chronicle:"开启变法"},
     {text:"有限改革，循序渐进",effects:{governance:10,economy:8,morale:3},risk:0.1,chronicle:"渐进改革"},
     {text:"维持旧制，以稳为主",effects:{morale:8,governance:-3},risk:0.05,chronicle:"维持旧制"},
     {text:"令两派各治国事以观其效",effects:{governance:12,diplomacy:5,risk:0.2},risk:0.2,chronicle:"两派各治国事"}
   ]},
  {id:"shared_succession_foreign",year:-300,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"邻国嗣君之变",
   text:"邻国老君薨逝，新君年少即位，国势动荡。有大臣以为此乃天赐良机，主张趁机出兵；也有人以为此时出兵恐失道义于天下。",
   choices:[
     {text:"趁机出兵，攻城略地",effects:{military:15,economy:-10,diplomacy:-12,morale:-5},risk:0.3,chronicle:"趁邻国丧君出兵",territoryEffect:{gain:true,from:"韩"}},
     {text:"遣使吊唁，示以善意",effects:{diplomacy:15,morale:5,governance:3},risk:0.05,chronicle:"遣使吊唁邻国新君"},
     {text:"支持邻国宗室中的亲我势力",effects:{diplomacy:12,governance:5,economy:-5},risk:0.2,chronicle:"支持邻国亲我势力"},
     {text:"按兵不动，静观其变",effects:{military:3,governance:5,morale:3},risk:0.05,chronicle:"静观邻国局势"}
   ]},
  {id:"shared_military_reform",year:-280,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"军制革新",
   text:"有知兵之将上疏，建议改革军制：或效秦之二十等爵制，赏军功；或学魏之武卒制，精选拔。然大刀阔斧改革，恐引起守旧将领不满。",
   choices:[
     {text:"全面推行军功爵制",effects:{military:18,morale:8,governance:-5,economy:-8},risk:0.2,chronicle:"推行军功爵制"},
     {text:"局部改良，精选士卒",effects:{military:10,economy:-3,governance:5},risk:0.1,chronicle:"局部军制改良"},
     {text:"维持现有军制不动",effects:{morale:3,military:-5},risk:0.0,chronicle:"维持现有军制"},
     {text:"令各将领自定选兵之法",effects:{military:8,governance:-3,morale:5},risk:0.15,chronicle:"各将领自定选兵法"}
   ]},
  {id:"shared_court_intrigue",year:-260,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"后宫干政",
   text:"后宫嫔妃与外朝大臣暗通款曲，干预朝政。有御史弹劾之，然后宫势力盘根错节，牵连甚广。王若深究，恐动摇宫廷根基；若不问，则朝纲不振。",
   choices:[
     {text:"雷霆手段，肃清后宫",effects:{governance:15,morale:8,diplomacy:-5},risk:0.25,chronicle:"肃清后宫",
      rulerFate:{type:"被毒杀",chance:0.1,text:"后宫势力反噬",chronicle:"肃清后宫不成，反遭毒杀"}},
     {text:"点到为止，只惩首恶",effects:{governance:8,morale:5},risk:0.1,chronicle:"只惩后宫首恶"},
     {text:"不予追究，息事宁人",effects:{governance:-8,morale:-5},risk:0.05,chronicle:"息事宁人"},
     {text:"将后宫干政者遣送离宫",effects:{governance:10,morale:5,diplomacy:3},risk:0.15,chronicle:"遣送后宫干政者"}
   ]},
  {id:"shared_assassination_attempt",year:-240,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"刺杀未遂",
   text:"王于宫中宴饮，忽有刺客自梁上跃下，持刃直向王座。幸得侍卫奋不顾身，刺客未能得逞。然主谋者谁？是敌国奸细？还是朝中政敌？",
   choices:[
     {text:"严刑拷问刺客，追查幕后",effects:{governance:12,military:5,morale:3},risk:0.15,chronicle:"追查刺杀幕后"},
     {text:"借此事大清洗，清除异己",effects:{governance:8,military:5,morale:-12},risk:0.25,chronicle:"借刺杀之事清除异己",
      rulerFate:{type:"被弑",chance:0.12,text:"清洗过激，引发兵变",chronicle:"清洗过激，引发兵变被弑"}},
     {text:"大事化小，以安人心",effects:{morale:8,governance:-3},risk:0.05,chronicle:"大事化小"},
     {text:"加强宫禁护卫，不再深究",effects:{governance:5,military:8},risk:0.05,chronicle:"加强宫禁护卫"}
   ]},
  {id:"shared_hegemon_demand",year:-220,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"霸主索贡",
   text:"当世霸主遣使来朝，要求我国割地纳贡，以示臣服。若拒之，恐招兵祸；若从之，则国格受损、百姓怨愤。使者趾高气扬，群臣怒不敢言。",
   choices:[
     {text:"断然拒绝，宁死不屈",effects:{military:10,morale:15,diplomacy:-12},risk:0.4,chronicle:"拒绝霸主要求",
      rulerFate:{type:"战死",chance:0.15,text:"霸主来伐，兵败身死",chronicle:"拒绝纳贡，大国来伐兵败身死"}},
     {text:"虚与委蛇，表面顺从",effects:{diplomacy:8,morale:-10,economy:-8},risk:0.1,chronicle:"表面顺从霸主"},
     {text:"割地纳贡，以求苟安",effects:{diplomacy:5,morale:-18,military:-8},risk:0.05,chronicle:"割地纳贡"},
     {text:"厚赂使者，拖延时日",effects:{economy:-10,diplomacy:8,military:3},risk:0.15,chronicle:"贿赂使者拖延时日"}
   ]},
  {id:"shared_tech_discovery",year:-200,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"冶铁术突破",
   text:"工匠在试验中偶然发现新的冶铁配方，可使兵器更加锋利坚固。若将此技术用于军备，我军的战斗力将大幅提升。然推广新技术需大量资金。",
   choices:[
     {text:"全力推广，改造全军装备",effects:{military:15,economy:-15,governance:5},risk:0.15,chronicle:"推广新冶铁技术"},
     {text:"先在精锐部队中试用",effects:{military:10,economy:-5},risk:0.05,chronicle:"精锐部队先试用新装备"},
     {text:"贩卖技术换取黄金",effects:{economy:15,diplomacy:5,military:-3},risk:0.1,chronicle:"贩卖冶铁技术"},
     {text:"封存技术，秘密研发",effects:{military:8,governance:5},risk:0.05,chronicle:"秘密研发新兵器"}
   ]},
  {id:"shared_refugee_crisis",year:-180,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"流民入国",
   text:"邻国因战乱天灾，大批流民涌入我国边境。流民中混杂着不少青壮年，亦有不法之徒。边将请旨如何处置？",
   choices:[
     {text:"开边境接纳流民，编户齐民",effects:{economy:12,morale:10,governance:-5},risk:0.1,chronicle:"接纳流民编户"},
     {text:"只选青壮年入伍，余者遣返",effects:{military:12,economy:-3,morale:-5},risk:0.1,chronicle:"精选流民入伍"},
     {text:"紧闭边境，遣返全部流民",effects:{morale:-10,governance:8,diplomacy:-5},risk:0.05,chronicle:"遣返流民"},
     {text:"令流民屯田开荒，自食其力",effects:{economy:10,governance:8,military:-3},risk:0.1,chronicle:"令流民屯田"}
   ]},
  {id:"shared_secret_alliance",year:-160,era:[1,2,3,4,5,6],condition:{countries:["秦","齐","楚","赵","魏","韩","燕"]},title:"秘密盟约",
   text:"有邻国密使深夜来访，言愿与我国结为秘密同盟，共同对付第三方。使者带来盟书与厚礼，然此事若败露，我国将面临极大外交压力。",
   choices:[
     {text:"欣然签约，结秘密盟约",effects:{diplomacy:12,military:10,governance:-5},risk:0.25,chronicle:"缔结秘密同盟"},
     {text:"婉拒密约，保持公开外交",effects:{diplomacy:-5,morale:5},risk:0.0,chronicle:"婉拒秘密盟约"},
     {text:"接纳盟约但暗中告密第三方",effects:{diplomacy:15,military:-3,morale:-8},risk:0.3,chronicle:"假意结盟实则告密"},
     {text:"将密使扣留，以此勒索对方",effects:{economy:10,diplomacy:-15,military:5},risk:0.2,chronicle:"扣留密使勒索对方"}
   ]},
];

const RANDOM_EVENTS = [
  {id:"random_famine",type:"内政",title:"天灾·饥荒",
   text:"今岁大旱，赤地千里，民不聊生。饥民流离失所，盗贼蜂起。卿当如何赈济？",
   choices:[
     {text:"开仓放粮，赈济灾民",effects:{economy:-15,morale:15,governance:5},risk:0.05,chronicle:"开仓赈灾，民心稍安"},
     {text:"以工代赈，修筑城防",effects:{economy:-10,military:10,morale:5},risk:0.1,chronicle:"以工代赈，修筑城防"},
     {text:"严刑峻法，镇压流民",effects:{morale:-15,governance:5,military:5},risk:0.2,chronicle:"镇压流民，民怨沸腾"}
   ]},
  {id:"random_harvest",type:"内政",title:"丰收之年",
   text:"今岁风调雨顺，五谷丰登，仓廪充实。百姓安居乐业，国泰民安。",
   choices:[
     {text:"减免赋税，与民休息",effects:{economy:10,morale:15,governance:5},risk:0.0,chronicle:"减免赋税，与民休息"},
     {text:"充实军粮，扩军备战",effects:{military:15,economy:5,morale:-5},risk:0.0,chronicle:"充实军粮，扩军备战"},
     {text:"修缮城池，加固防御",effects:{governance:10,military:5,economy:5},risk:0.0,chronicle:"修缮城池，加固防御"}
   ]},
  {id:"random_plague",type:"内政",title:"瘟疫流行",
   text:"大疫横行，死者枕藉。朝中大臣亦有染病者，人心惶惶。",
   choices:[
     {text:"广招医者，全力救治",effects:{economy:-10,morale:10,governance:5},risk:0.1,chronicle:"全力救治瘟疫"},
     {text:"封锁疫区，防止蔓延",effects:{morale:-10,governance:10,economy:-5},risk:0.1,chronicle:"封锁疫区"},
     {text:"祭祀天地，祈求平安",effects:{morale:5,governance:-5},risk:0.05,chronicle:"祭祀天地以祈平安"}
   ]},
  {id:"random_talent",type:"人才",title:"名士来投",
   text:"有游士闻我国招贤纳士，不远千里而来。此人博闻强识，谈吐不凡，似有大才。",
   choices:[
     {text:"委以重任，不拘一格",effects:{governance:10,diplomacy:5,morale:5},risk:0.2,chronicle:"重用外来名士",
      specialEffect:{chance:0.18,type:'character',pool:true}},
     {text:"先试其才，量才录用",effects:{governance:5,morale:3},risk:0.05,chronicle:"量才录用外来名士"},
     {text:"此人来路不明，不可轻信",effects:{diplomacy:-5},risk:0.0,chronicle:"未用外来名士"}
   ]},
  {id:"random_spy",type:"内政",title:"间谍渗透",
   text:"有司查获敌国间谍数名，已渗透朝中，窃取军政机密。事关重大，当如何处置？",
   choices:[
     {text:"严刑拷问，追根溯源",effects:{governance:10,military:5,morale:-5},risk:0.15,chronicle:"严查间谍，追根溯源"},
     {text:"将计就计，传递假情报",effects:{diplomacy:10,military:10},risk:0.3,chronicle:"将计就计，以间谍传假情报"},
     {text:"秘密处决，不事声张",effects:{governance:5,morale:5},risk:0.05,chronicle:"秘密处决间谍"}
   ]},
  {id:"random_border",type:"战争",title:"边境冲突",
   text:"边将来报：邻国军队越境劫掠，杀我边民，焚我粮仓。边将请战，群情激愤。",
   choices:[
     {text:"发兵反击，以牙还牙",effects:{military:10,diplomacy:-10,economy:-5},risk:0.35,chronicle:"发兵反击边境入侵"},
     {text:"遣使交涉，要求赔偿",effects:{diplomacy:5,military:-5,morale:-5},risk:0.1,chronicle:"遣使交涉边境冲突"},
     {text:"加强边防，不予理会",effects:{military:5,governance:5,diplomacy:0},risk:0.05,chronicle:"加强边防，暂不反击"}
   ]},
  {id:"random_rebellion",type:"内政",title:"贵族叛乱",
   text:"宗室贵族不满朝政，暗中联络外臣，欲行不轨。事泄，当如何处置？",
   choices:[
     {text:"雷霆镇压，杀一儆百",effects:{governance:10,morale:-10,military:5},risk:0.25,chronicle:"镇压贵族叛乱",
      rulerFate:{type:"被弑",chance:0.15,text:"镇压不成，反被贵族所弑",chronicle:"镇压叛乱不成，为贵族所弑"}},
     {text:"宽大为怀，赦免首恶",effects:{morale:10,governance:-5,diplomacy:5},risk:0.15,chronicle:"赦免叛乱贵族"},
     {text:"分化瓦解，各个击破",effects:{governance:8,diplomacy:5},risk:0.2,chronicle:"分化瓦解叛乱势力"}
   ]},
  {id:"random_alliance",type:"外交",title:"邻国求盟",
   text:"邻国遣使来朝，愿与我国结为盟好，共抗强敌。使者言辞恳切，携厚礼而来。",
   choices:[
     {text:"欣然接受，缔结同盟",effects:{diplomacy:15,military:5,economy:-5},risk:0.1,chronicle:"与邻国缔结同盟"},
     {text:"接受结盟，但要求对方割城为质",effects:{diplomacy:10,economy:10,military:5},risk:0.25,chronicle:"以割城为条件结盟"},
     {text:"婉拒结盟，保持中立",effects:{diplomacy:-5,morale:5},risk:0.05,chronicle:"婉拒结盟，保持中立"}
   ]},
  {id:"random_trade",type:"内政",title:"商路开通",
   text:"有商人请开新商路，通四方之货。若成，则国库充盈；然亦恐外国细作借此渗透。",
   choices:[
     {text:"大力支持，广开商路",effects:{economy:15,diplomacy:10,governance:-5},risk:0.1,chronicle:"广开商路，经济繁荣"},
     {text:"有限开放，严格管控",effects:{economy:8,governance:5},risk:0.05,chronicle:"有限开放商路"},
     {text:"闭关锁国，以防渗透",effects:{governance:5,economy:-5,diplomacy:-10},risk:0.0,chronicle:"闭关锁国"}
   ]},
  {id:"random_weapon",type:"内政",title:"兵器革新",
   text:"有工匠献新式兵器图纸，据称可大幅提升军力。然所需耗费巨大，且成败未卜。",
   choices:[
     {text:"拨重金研发新兵器",effects:{military:15,economy:-12},risk:0.3,chronicle:"拨重金研发新兵器"},
     {text:"小规模试验，观其成效",effects:{military:8,economy:-5},risk:0.15,chronicle:"小规模试验新兵器"},
     {text:"此乃奇技淫巧，不足取",effects:{military:-3,morale:3},risk:0.0,chronicle:"拒绝兵器革新"}
   ]},
  {id:"random_succession",type:"内政",title:"储位之争",
   text:"太子年幼，诸公子觊觎储位，朝中大臣各有所附。后宫亦不安宁，明争暗斗不休。",
   choices:[
     {text:"早立太子，以安人心",effects:{governance:10,morale:10},risk:0.1,chronicle:"早立太子，平息储位之争"},
     {text:"考察诸公子，择贤而立",effects:{governance:5,morale:-5},risk:0.2,chronicle:"考察诸公子，迟迟未立储"},
     {text:"以嫡长子继承，不偏不倚",effects:{governance:8,morale:5},risk:0.05,chronicle:"依嫡长制立储"}
   ]},
  {id:"random_flood",type:"内政",title:"洪水泛滥",
   text:"大雨连月不止，河水暴涨，淹没良田万顷，百姓流离失所。",
   choices:[
     {text:"征发民夫，修筑堤坝",effects:{economy:-10,governance:10,military:-5},risk:0.1,chronicle:"修筑堤坝，治理洪水"},
     {text:"迁移灾民，另辟新地",effects:{economy:-8,morale:5,governance:5},risk:0.05,chronicle:"迁移灾民"},
     {text:"开仓赈济，等待水退",effects:{economy:-12,morale:10},risk:0.05,chronicle:"开仓赈济水灾难民"}
   ]},
  {id:"random_mine",type:"内政",title:"发现矿脉",
   text:"有猎户于山中发现了铁矿矿脉，储量颇丰。若开采之，可充实军备与国库。",
   choices:[
     {text:"大规模开采，充实国力",effects:{economy:15,military:10,governance:-3},risk:0.05,chronicle:"大规模开采铁矿"},
     {text:"小规模开采，避免引人觊觎",effects:{economy:8,military:5},risk:0.0,chronicle:"小规模开采铁矿"},
     {text:"封存矿脉，以备后用",effects:{governance:3},risk:0.0,chronicle:"封存矿脉"}
   ]},
  {id:"random_marriage",type:"外交",title:"联姻之议",
   text:"邻国遣使求亲，欲与我国联姻。若许之，两国关系可进一步；然亦恐对方借联姻之名行渗透之实。",
   choices:[
     {text:"许以联姻，加强邦交",effects:{diplomacy:15,morale:5},risk:0.1,chronicle:"与邻国联姻"},
     {text:"婉拒联姻，保持距离",effects:{diplomacy:-5,morale:3},risk:0.0,chronicle:"婉拒联姻"},
     {text:"许以联姻，但暗中监视",effects:{diplomacy:10,governance:5},risk:0.15,chronicle:"联姻同时暗中监视"}
   ]},
  {id:"random_philosopher",type:"人才",title:"百家争鸣",
   text:"有诸子百家之学者聚于国中，各持其说，辩论不休。儒者言仁义，法者言刑名，墨者言兼爱，兵者言攻守。",
   choices:[
     {text:"广纳百家，兼容并蓄",effects:{governance:10,diplomacy:5,morale:5},risk:0.05,chronicle:"广纳百家之学",
      specialEffect:{chance:0.12,type:'character',pool:true}},
     {text:"独尊一家，统一思想",effects:{governance:15,morale:-10},risk:0.15,chronicle:"独尊一家之学"},
     {text:"不予理会，任其自生自灭",effects:{governance:-3},risk:0.0,chronicle:"未理会百家争鸣"}
   ]},
  {id:"random_general_defect",type:"战争",title:"敌将来降",
   text:"有敌国名将因遭猜忌，率部来降。此人骁勇善战，若用之可大增军力；然其忠诚度存疑。",
   choices:[
     {text:"欣然接纳，委以重任",effects:{military:15,diplomacy:-10},risk:0.35,chronicle:"接纳敌国降将",
      specialEffect:{chance:0.15,type:'character',pool:true}},
     {text:"接纳但限制其兵权",effects:{military:8,diplomacy:-5},risk:0.15,chronicle:"接纳降将但限制兵权"},
     {text:"此人反复无常，不可信",effects:{diplomacy:5,military:-3},risk:0.0,chronicle:"拒绝接纳降将"}
   ]},
  {id:"random_earthquake",type:"内政",title:"地动山摇",
   text:"大地震动，城墙崩塌，房屋倾倒，死伤无数。百姓惊恐，以为天罚。",
   choices:[
     {text:"全力救灾，重建家园",effects:{economy:-15,morale:15,governance:5},risk:0.05,chronicle:"全力救灾地震"},
     {text:"先修城防，以防外敌趁虚而入",effects:{military:10,economy:-10,morale:-5},risk:0.1,chronicle:"优先修复城防"},
     {text:"祭祀天地，安抚民心",effects:{morale:8,economy:-5,governance:-3},risk:0.0,chronicle:"祭祀天地以安民心"}
   ]},
  {id:"random_nomad",type:"战争",title:"胡人犯边",
   text:"北方游牧部族大举南侵，劫掠边城，杀我百姓。边将告急，请朝廷速发援兵。",
   choices:[
     {text:"发大军北击，彻底解决边患",effects:{military:15,economy:-15},risk:0.4,chronicle:"发大军北击胡人"},
     {text:"增派援军，坚守城池",effects:{military:8,economy:-8},risk:0.2,chronicle:"增援边城，坚守不出"},
     {text:"以财物贿赂胡人，使其退兵",effects:{economy:-10,diplomacy:5,military:-5},risk:0.1,chronicle:"以财物贿赂胡人"}
   ]},
  {id:"random_corruption",type:"内政",title:"贪腐横行",
   text:"有司查出朝中多名大臣贪赃枉法，中饱私囊。涉案金额巨大，牵连甚广。",
   choices:[
     {text:"铁腕反腐，严惩不贷",effects:{governance:15,morale:10,economy:5},risk:0.2,chronicle:"铁腕反腐，严惩贪官"},
     {text:"杀鸡儆猴，只惩首恶",effects:{governance:8,morale:5},risk:0.1,chronicle:"惩治贪腐首恶"},
     {text:"法不责众，从轻发落",effects:{governance:-10,morale:-5},risk:0.05,chronicle:"从轻发落贪官"}
   ]},
  {id:"random_canal",type:"内政",title:"兴修水利",
   text:"有大臣建议兴修大型水利工程，引水灌溉，可增良田万顷。然工程浩大，耗时费财。",
   choices:[
     {text:"批准工程，利在千秋",effects:{economy:20,governance:5,military:-5},risk:0.1,chronicle:"兴修大型水利工程"},
     {text:"分期建设，量力而行",effects:{economy:10,governance:3},risk:0.05,chronicle:"分期建设水利工程"},
     {text:"国力不济，暂缓建设",effects:{economy:-3,morale:-3},risk:0.0,chronicle:"暂缓水利建设"}
   ]},
  {id:"random_invasion",type:"战争",title:"强敌来犯",
   text:"强敌大举来犯，敌军数倍于我。城下黑云压阵，城内人心惶惶。是战是降，一念之间。",
   choices:[
     {text:"背城一战，誓死守城",effects:{military:12,morale:15,economy:-15},risk:0.45,chronicle:"背城一战",
      rulerFate:{type:"战死",chance:0.3,text:"城破身死",chronicle:"守城失败，战死城下"}},
     {text:"坚壁清野，消耗敌军",effects:{military:5,economy:-12,morale:8},risk:0.25,chronicle:"坚壁清野"},
     {text:"遣使求和，割地退兵",effects:{diplomacy:5,morale:-15,military:-8},risk:0.1,chronicle:"割地求和"},
     {text:"弃城而走，保存实力",effects:{military:-5,morale:-12,economy:5},risk:0.15,chronicle:"弃城而走",territoryEffect:{lose:true,to:"秦"}}
   ]},
  {id:"random_adviser_dies",type:"人才",title:"重臣病逝",
   text:"朝中股肱之臣突染重病，药石无医，数日而卒。此人生前为朝堂重镇，他的离世让朝局出现空缺。",
   choices:[
     {text:"隆重安葬，从子弟中选人继任",effects:{governance:8,morale:10,economy:-5},risk:0.1,chronicle:"厚葬重臣"},
     {text:"不拘一格，从他国招贤补缺",effects:{governance:10,diplomacy:8,economy:-3},risk:0.15,chronicle:"招贤补缺"},
     {text:"亲自主持朝政，填补权力真空",effects:{governance:15,diplomacy:-5,morale:5},risk:0.1,chronicle:"亲自主持朝政"}
   ]},
  {id:"random_city_revolt",type:"内政",title:"边城叛乱",
   text:"边城百姓因徭役过重，聚众反叛。守将被杀，叛军占据城池。若不及时平息，恐他城效仿。",
   choices:[
     {text:"发兵镇压，震慑叛乱",effects:{military:8,governance:5,morale:-10},risk:0.2,chronicle:"发兵镇压边城叛乱"},
     {text:"减免徭役，安抚叛民",effects:{morale:12,economy:-5,governance:5},risk:0.1,chronicle:"减免徭役安抚叛民"},
     {text:"围而不攻，断其粮草迫降",effects:{military:5,governance:3,economy:-3},risk:0.15,chronicle:"围城断粮迫降叛民"},
     {text:"令地方豪族出面调解",effects:{diplomacy:8,governance:3,morale:5},risk:0.1,chronicle:"令豪族调解边城叛乱"}
   ]},
  {id:"random_merchant_guild",type:"内政",title:"商人请命",
   text:"全国大商贾联名上疏，请朝廷统一度量衡、铸造官币以便贸易。此举利于商业，然铸币需大量铜铁，恐与兵器制造争利。",
   choices:[
     {text:"统一度量衡，铸造官币",effects:{economy:15,governance:8,diplomacy:5},risk:0.1,chronicle:"统一度量衡铸官币"},
     {text:"先统一度量衡，暂不铸币",effects:{economy:10,governance:5},risk:0.05,chronicle:"统一度量衡"},
     {text:"铜铁优先供军需，商人之请暂缓",effects:{military:5,economy:-3,morale:-3},risk:0.0,chronicle:"优先军事暂缓商业"},
     {text:"允许私人铸币，朝廷监管",effects:{economy:12,governance:-5},risk:0.15,chronicle:"允私人铸币朝廷监管"}
   ]},
  {id:"random_foreign_prince",type:"外交",title:"质子来朝",
   text:"邻国为表诚意，遣太子来我国为质子。然朝中有大臣以为此乃对方欲松懈我防备之心。应如何对待这位质子？",
   choices:[
     {text:"以礼相待，厚待质子",effects:{diplomacy:15,morale:5,economy:-3},risk:0.05,chronicle:"厚待邻国质子"},
     {text:"令质子学习我国制度，培养亲我势力",effects:{diplomacy:12,governance:8},risk:0.1,chronicle:"培养亲我质子",
      specialEffect:{chance:0.15,type:'character',pool:true}},
     {text:"质子不过是人质，不必大张旗鼓",effects:{diplomacy:-5,morale:3},risk:0.05,chronicle:"冷遇邻国质子"},
     {text:"将质子遣返，以示信任",effects:{diplomacy:18,morale:8,governance:3},risk:0.15,chronicle:"遣返质子以示信任"}
   ]},
  {id:"random_bandits",type:"内政",title:"山贼为患",
   text:"境内山中盗贼蜂起，劫掠商旅，攻取小县。地方官员束手无策，请朝廷发兵进剿。然贼据天险，易守难攻。",
   choices:[
     {text:"发兵清剿，斩草除根",effects:{military:5,governance:8,morale:5},risk:0.2,chronicle:"发兵清剿山贼"},
     {text:"招安为上，编贼为兵",effects:{military:10,governance:5,morale:-3},risk:0.15,chronicle:"招安山贼编为兵"},
     {text:"安抚地方，以治本为主",effects:{governance:12,morale:8},risk:0.05,chronicle:"安抚地方治本"},
     {text:"令地方豪强自行组织民兵",effects:{military:3,governance:-5,morale:5},risk:0.1,chronicle:"令豪强组织民兵"}
   ]},
  {id:"random_astrologer",type:"内政",title:"太卜预言",
   text:"太卜夜观天象，言荧惑守心，主兵灾；又见紫微暗淡，以为国有大变。此言一出，朝野震动。王应如何处置太卜之言？",
   choices:[
     {text:"修德省身，大赦天下以禳灾",effects:{morale:12,governance:3,economy:-5},risk:0.05,chronicle:"修德禳灾大赦天下"},
     {text:"妖言惑众，将太卜下狱",effects:{morale:-5,governance:8},risk:0.1,chronicle:"镇压太卜预言"},
     {text:"令太卜再观天象，仔细推算",effects:{morale:5,governance:3},risk:0.05,chronicle:"令太卜再观"},
     {text:"借助天象厉行改革",effects:{governance:12,morale:5,military:3},risk:0.1,chronicle:"借天象厉行改革"}
   ]},
  {id:"random_grain_hoarding",type:"内政",title:"粮商囤积",
   text:"大粮商囤积居奇，粮价飞涨。百姓买不起粮，怨声载道。地方官员奏请朝廷开仓平抑粮价。",
   choices:[
     {text:"开仓放粮，平抑粮价",effects:{morale:15,economy:-10,governance:5},risk:0.05,chronicle:"开仓平抑粮价"},
     {text:"严惩粮商，没收囤粮",effects:{morale:10,governance:8,economy:3},risk:0.15,chronicle:"严惩粮商"},
     {text:"与粮商谈判，令其降价",effects:{economy:5,governance:3,morale:5},risk:0.1,chronicle:"与粮商谈判"},
     {text:"不予干预，由市场自行调节",effects:{morale:-10,governance:-3},risk:0.05,chronicle:"放任粮价上涨"}
   ]},
  {id:"random_deserter",type:"战争",title:"前线逃兵",
   text:"前线来报，近日有士兵私逃回乡。经查，是因家中遭灾无人照料，非有叛逆之心。依军法，逃兵当斩；然法不责众，若一概处斩，恐寒了军心。",
   choices:[
     {text:"按军法严惩，以儆效尤",effects:{military:5,morale:-10,governance:5},risk:0.1,chronicle:"按军法严惩逃兵"},
     {text:"法外施恩，令逃兵戴罪立功",effects:{morale:12,military:5,governance:-3},risk:0.05,chronicle:"令逃兵戴罪立功"},
     {text:"优待军属，解决后顾之忧",effects:{morale:15,governance:8,economy:-5},risk:0.05,chronicle:"优待军属"},
     {text:"斩首恶，赦从者",effects:{military:3,governance:5,morale:5},risk:0.1,chronicle:"斩首恶赦从者"}
   ]},
  {id:"random_political_marriage",type:"外交",title:"和亲之议",
   text:"有大臣提议，以外嫁宗室女与邻国和亲，以巩固邦交。然宗室之女亦有不愿远嫁者。此举可安邦国，但有悖人伦之情。",
   choices:[
     {text:"答应和亲，巩固邦交",effects:{diplomacy:15,morale:-3},risk:0.05,chronicle:"与邻国和亲"},
     {text:"以民间女子假充宗室",effects:{diplomacy:8,morale:3,governance:-3},risk:0.2,chronicle:"以民女假充宗室女"},
     {text:"婉拒和亲，以他法结好",effects:{diplomacy:-5,morale:8},risk:0.05,chronicle:"婉拒和亲"},
     {text:"反向提亲，令对方嫁女过来",effects:{diplomacy:5,morale:5},risk:0.1,chronicle:"反向提亲"}
   ]},
  {id:"random_water_poison",type:"内政",title:"水源被投毒",
   text:"国都城外水源被人投毒，数百百姓饮水而亡。凶手未知，城中恐慌。有大臣疑为敌国奸细所为，主张大索全城。",
   choices:[
     {text:"大索全城，缉拿奸细",effects:{governance:8,military:5,morale:-3},risk:0.15,chronicle:"大索全城缉拿奸细"},
     {text:"封井消毒，安抚百姓",effects:{morale:10,governance:3,economy:-5},risk:0.05,chronicle:"封井消毒安抚百姓"},
     {text:"以此为机加强城防治安",effects:{governance:12,military:5,economy:-3},risk:0.05,chronicle:"加强城防治安"},
     {text:"祭祀水源，祈求平安",effects:{morale:5,governance:-3},risk:0.05,chronicle:"祭祀水源"}
   ]},
  {id:"random_silk_monopoly",type:"内政",title:"盐铁之议",
   text:"有大臣建议将盐铁收归官营，以充国用。商人反对甚烈，以为官营必致腐败低效。然若行之，国库可大增。",
   choices:[
     {text:"盐铁官营，充实国库",effects:{economy:18,governance:8,morale:-8},risk:0.15,chronicle:"盐铁官营"},
     {text:"盐官营，铁民营",effects:{economy:12,governance:5,morale:3},risk:0.1,chronicle:"盐官营铁民营"},
     {text:"维持民营，加征税赋",effects:{economy:10,morale:-5},risk:0.05,chronicle:"加征盐铁税"},
     {text:"委托大商贾承包经营",effects:{economy:13,governance:-5},risk:0.15,chronicle:"委托商贾承包盐铁"}
   ]},
  {id:"random_hermit_advice",type:"人才",title:"隐士献策",
   text:"隐于山林的贤士托人递上一策，言可助国家富强。其策甚奇，与传统治国之道迥异。朝臣多不信之，以为荒诞不经。",
   choices:[
     {text:"亲赴山林，当面请教",effects:{governance:15,diplomacy:8,morale:5},risk:0.1,chronicle:"亲赴山林请教隐士",
      specialEffect:{chance:0.2,type:'character',pool:true}},
     {text:"遣重臣携厚礼往聘",effects:{governance:12,economy:-5},risk:0.08,chronicle:"聘隐士出山"},
     {text:"先试其策于一小县，观其效",effects:{governance:8,morale:3},risk:0.1,chronicle:"小范围试验隐士之策"},
     {text:"荒诞不经，不予理会",effects:{governance:-3,morale:-3},risk:0.0,chronicle:"未采纳隐士之策"}
   ]},
  {id:"random_city_expansion",type:"内政",title:"扩建都城",
   text:"都城人口日增，旧城不敷使用。有大臣建议扩建新城区，修筑高墙以壮国威。然工程浩大，役民数万。",
   choices:[
     {text:"大兴土木，扩建都城",effects:{governance:12,economy:-15,morale:-5},risk:0.1,chronicle:"扩建都城"},
     {text:"逐步扩建，量力而行",effects:{governance:8,economy:-5,morale:3},risk:0.05,chronicle:"逐步扩建都城"},
     {text:"疏解人口至周边城池",effects:{economy:5,governance:5,military:3},risk:0.05,chronicle:"疏解都城人口"},
      {text:"暂缓扩建，以边防为先",effects:{military:8,governance:-3},risk:0.05,chronicle:"暂缓扩城优先边防"}
    ]},
  {id:"random_war_ambush",type:"战争",title:"伏击良机",
   text:"探马来报：邻国运粮队将于三日后经过山谷小道，护卫薄弱。若能伏击得手，可断其前线粮草，趁乱攻城。然此山谷地形复杂，若走漏消息反遭埋伏。",
   choices:[
     {text:"派遣精锐伏击，趁乱攻城",effects:{military:12,economy:8,diplomacy:-10},risk:0.35,chronicle:"伏击敌粮队，趁乱攻城",
      territoryEffect:{gain:true,from:"魏"}},
     {text:"谨慎为上，放过此机",effects:{military:3,governance:5},risk:0.0,chronicle:"放过伏击之机"},
     {text:"佯装伏击，实则绕道直取其城",effects:{military:15,economy:-5,diplomacy:-8},risk:0.4,chronicle:"声东击西取城",
      territoryEffect:{gain:true,from:"韩"}},
     {text:"散布假消息，诱敌出击再歼灭",effects:{military:10,diplomacy:5,governance:5},risk:0.25,chronicle:"诱敌出战歼之"}
   ]},
  {id:"random_war_siege",type:"战争",title:"围城之战",
   text:"我军包围敌国边城已逾一月，城中粮尽，守军疲惫。然敌国援军正在逼近。是继续围困待其自溃，还是强攻破城，或是撤围以避援军？",
   choices:[
     {text:"继续围困，待其自溃",effects:{military:5,economy:-8,governance:3},risk:0.25,chronicle:"续围边城至其降",
      territoryEffect:{gain:true,from:"赵"}},
     {text:"强攻破城，速战速决",effects:{military:8,economy:-5,governance:-3},risk:0.35,chronicle:"强攻边城克之",
      territoryEffect:{gain:true,from:"魏"}},
     {text:"撤围退兵，保存实力",effects:{military:-3,economy:5,diplomacy:3},risk:0.05,chronicle:"撤围退兵"},
     {text:"分兵阻击援军，主力继续围城",effects:{military:10,economy:-12},risk:0.3,chronicle:"围点打援",
      territoryEffect:{gain:true,from:"楚"}}
   ]},
  {id:"random_war_rebellion_neighbor",type:"战争",title:"邻国边城叛降",
   text:"邻国边境守将因与国中权臣有隙，遣密使来献城。若接纳此城，必与邻国交恶；若不纳，则错失天赐良机。",
   choices:[
     {text:"欣然纳城，收编降军",effects:{military:8,economy:5,diplomacy:-15,morale:5},risk:0.2,chronicle:"纳降收城",
      territoryEffect:{gain:true,from:"韩"}},
     {text:"暗中支持守将自立，不直接卷入",effects:{diplomacy:10,governance:5,diplomacy:-5,morale:3},risk:0.15,chronicle:"暗中支持守将独立"},
     {text:"婉拒密使，不想引火上身",effects:{diplomacy:3,morale:-5},risk:0.0,chronicle:"婉拒纳降"},
     {text:"佯装拒绝，暗派援军助其抵御",effects:{military:5,diplomacy:8,economy:-8},risk:0.25,chronicle:"暗派援军助守将"}
   ]},
  {id:"random_war_raid",type:"战争",title:"奇袭敌后",
   text:"有将献奇计：选精骑三千，绕道敌后，焚其粮仓、断其归路，前后夹击可大破敌军。然此计甚险，若不成则精骑有去无回。",
   choices:[
     {text:"从奇计，遣精骑奇袭",effects:{military:15,economy:-8,diplomacy:-3},risk:0.4,chronicle:"精骑奇袭敌后",
      territoryEffect:{gain:true,from:"齐"}},
     {text:"仍用正兵，稳扎稳打",effects:{military:8,economy:-10,governance:3},risk:0.15,chronicle:"正兵稳步推进"},
     {text:"散播奇袭谣言，诱敌分兵再击其弱势",effects:{military:10,governance:5,diplomacy:3},risk:0.2,chronicle:"虚张声势诱敌分兵",
      territoryEffect:{gain:true,from:"赵"}},
     {text:"暂不进攻，派间谍渗透",effects:{governance:8,diplomacy:5,military:3},risk:0.1,chronicle:"间谍渗透敌后"}
   ]},
  {id:"random_war_river",type:"战争",title:"渡河会战",
   text:"大军已至河畔，敌在对岸严阵以待。河水湍急，渡河不易。有将主张强渡，有将建议绕道上游涉浅。双方争执不下。",
   choices:[
     {text:"强渡大河，背水一战",effects:{military:12,morale:10,economy:-12},risk:0.4,chronicle:"背水强渡克敌",
      territoryEffect:{gain:true,from:"秦"}},
     {text:"绕道上游，安全渡河",effects:{military:5,economy:-5,governance:3},risk:0.1,chronicle:"绕道上游渡河"},
     {text:"隔河对峙，待敌先动",effects:{military:3,economy:-8},risk:0.15,chronicle:"隔河对峙"},
     {text:"佯装强渡正面，暗遣偏师从下游偷袭",effects:{military:14,economy:-8,diplomacy:-5},risk:0.3,chronicle:"声东击西渡河",
      territoryEffect:{gain:true,from:"魏"}}
   ]},
];

// ── 特殊人物池（按国家分，奇遇事件概率触发）──
const SPECIAL_CHARACTERS = [
  // ── 秦 ──
  {id:"s_qin_01",name:"甘罗",type:"谋士",country:"秦",born:-260,died:-200,military:20,governance:60,diplomacy:88,strategy:82,loyalty:85,desc:"十二岁拜上卿，使赵得五城。少年奇才。"},
  {id:"s_qin_02",name:"郑国",type:"文官",country:"秦",born:-280,died:-220,military:5,governance:85,diplomacy:55,strategy:70,loyalty:65,desc:"韩国水工，为间入秦修渠。郑国渠成，关中沃野。"},
  {id:"s_qin_03",name:"李冰",type:"文官",country:"秦",born:-300,died:-240,military:10,governance:90,diplomacy:30,strategy:55,loyalty:80,desc:"治水大家，修都江堰。蜀地由此成天府之国。"},
  {id:"s_qin_04",name:"尉缭",type:"谋士",country:"秦",born:-270,died:-210,military:75,governance:60,diplomacy:55,strategy:88,loyalty:70,desc:"兵家，著《尉缭子》。为秦王献灭六国大略。"},
  // ── 齐 ──
  {id:"s_qi_01",name:"鲁仲连",type:"谋士",country:"齐",born:-305,died:-245,military:15,governance:60,diplomacy:92,strategy:88,loyalty:85,desc:"齐国高士，排难解纷。助信陵君救赵，义不帝秦。"},
  {id:"s_qi_02",name:"扁鹊",type:"谋士",country:"齐",born:-401,died:-310,military:5,governance:60,diplomacy:55,strategy:70,loyalty:75,desc:"神医，望闻问切。能起死回生，名闻天下。"},
  {id:"s_qi_03",name:"邹衍",type:"谋士",country:"齐",born:-340,died:-280,military:5,governance:70,diplomacy:82,strategy:85,loyalty:80,desc:"阴阳家集大成者。论五德终始，天下九州。"},
  {id:"s_qi_04",name:"淳于髡",type:"文官",country:"齐",born:-380,died:-310,military:10,governance:75,diplomacy:88,strategy:72,loyalty:80,desc:"稷下辩士，以隐语谏齐王。一鸣惊人之喻出于其口。"},
  // ── 楚 ──
  {id:"s_chu_01",name:"宋玉",type:"文官",country:"楚",born:-298,died:-240,military:10,governance:70,diplomacy:80,strategy:65,loyalty:78,desc:"辞赋大家，屈原弟子。阳春白雪，曲高和寡。"},
  {id:"s_chu_02",name:"汗明",type:"谋士",country:"楚",born:-290,died:-240,military:20,governance:65,diplomacy:82,strategy:78,loyalty:80,desc:"楚国说客，以千里马喻劝春申君用贤。"},
  {id:"s_chu_03",name:"庄辛",type:"文官",country:"楚",born:-320,died:-260,military:15,governance:78,diplomacy:70,strategy:72,loyalty:85,desc:"谏臣，以蜻蜓黄雀之喻警楚襄王。亡羊补牢，未为晚也。"},
  {id:"s_chu_04",name:"老莱子",type:"谋士",country:"楚",born:-350,died:-280,military:5,governance:62,diplomacy:75,strategy:80,loyalty:90,desc:"道家隐士，孝感天下。楚王闻其贤，欲拜为相。"},
  // ── 赵 ──
  {id:"s_zhao_01",name:"毛遂",type:"文官",country:"赵",born:-310,died:-250,military:30,governance:70,diplomacy:88,strategy:72,loyalty:85,desc:"平原君门客，自荐使楚。三寸舌强于百万之师。"},
  {id:"s_zhao_02",name:"荀子",type:"谋士",country:"赵",born:-313,died:-238,military:10,governance:88,diplomacy:50,strategy:70,loyalty:80,desc:"儒学大师，三为稷下祭酒。著《荀子》，倡性恶论。"},
  {id:"s_zhao_03",name:"公孙龙",type:"谋士",country:"赵",born:-325,died:-250,military:5,governance:55,diplomacy:85,strategy:80,loyalty:75,desc:"名家巨擘，白马非马之说震古烁今。平原君客卿。"},
  {id:"s_zhao_04",name:"马服君",type:"武将",country:"赵",born:-320,died:-260,military:82,governance:50,diplomacy:30,strategy:75,loyalty:85,desc:"赵奢，阏与之战大败秦军。子括虽败，父实名将。"},
  // ── 魏 ──
  {id:"s_wei_01",name:"朱亥",type:"武将",country:"魏",born:-300,died:-250,military:78,governance:15,diplomacy:10,strategy:40,loyalty:90,desc:"大梁屠夫，勇力过人。椎杀晋鄙，助信陵君窃符救赵。"},
  {id:"s_wei_02",name:"候嬴",type:"谋士",country:"魏",born:-310,died:-257,military:20,governance:55,diplomacy:75,strategy:90,loyalty:80,desc:"夷门监者，年七十献窃符计。信陵君至赵，北向自刭以谢。"},
  {id:"s_wei_03",name:"唐雎",type:"文官",country:"魏",born:-280,died:-220,military:40,governance:65,diplomacy:90,strategy:78,loyalty:88,desc:"使秦不辱。布衣之怒，流血五步，天下缟素。"},
  {id:"s_wei_04",name:"缩高",type:"武将",country:"魏",born:-300,died:-250,military:72,governance:25,diplomacy:15,strategy:55,loyalty:80,desc:"隐退老将，虽年迈而勇。忠义两全，不背君亦不负子。"},
  {id:"s_wei_05",name:"王诩",type:"谋士",country:"魏",born:-380,died:-300,military:50,governance:70,diplomacy:85,strategy:95,loyalty:60,desc:"号鬼谷子，纵横捭阖之术。孙膑庞涓之师，来去无踪。"},
  // ── 韩 ──
  {id:"s_han_01",name:"郑国",type:"文官",country:"韩",born:-290,died:-230,military:5,governance:85,diplomacy:55,strategy:70,loyalty:65,desc:"水工，本韩间入秦。然郑国渠成，为间反为功，关中沃野。"},
  {id:"s_han_02",name:"张良",type:"谋士",country:"韩",born:-270,died:-186,military:30,governance:60,diplomacy:80,strategy:95,loyalty:90,desc:"韩相世家，博浪沙刺秦。后为汉初三杰之首。"},
  {id:"s_han_03",name:"韩凭",type:"文官",country:"韩",born:-300,died:-260,military:15,governance:72,diplomacy:60,strategy:58,loyalty:85,desc:"韩国能臣。善理财治政，韩赖以支秦数十年。"},
  {id:"s_han_04",name:"严仲子",type:"文官",country:"韩",born:-420,died:-380,military:25,governance:68,diplomacy:78,strategy:70,loyalty:80,desc:"韩大夫，与相侠累有隙。以百金结交聂政报私仇。"},
  // ── 燕 ──
  {id:"s_yan_01",name:"田光",type:"谋士",country:"燕",born:-280,died:-227,military:40,governance:55,diplomacy:82,strategy:78,loyalty:90,desc:"燕国义士，荐荆轲于太子丹。事成而自刎以明不泄之志。"},
  {id:"s_yan_02",name:"高渐离",type:"刺客",country:"燕",born:-270,died:-221,military:55,governance:15,diplomacy:25,strategy:35,loyalty:92,desc:"击筑名家，荆轲挚友。铅筑击秦王，虽死犹烈。"},
  {id:"s_yan_03",name:"郭隗",type:"文官",country:"燕",born:-350,died:-290,military:10,governance:78,diplomacy:82,strategy:62,loyalty:88,desc:"燕昭王师，献千金买骨之计。自隗始而天下贤才至。"},
  {id:"s_yan_04",name:"鞠武",type:"谋士",country:"燕",born:-280,died:-225,military:20,governance:60,diplomacy:75,strategy:78,loyalty:85,desc:"太子丹太傅。谏丹勿因私怨触怒强秦，献策合纵抗秦。"},
];
